/* ============================================================
   extra-dict.js — supplemental dictionary for the click word-breakdown.
   High-frequency instruction / exercise / grammar tokens that appear in
   lesson sentences but weren't in any vocab table, so some sentences had
   no breakdown on click. These feed ONLY the breakdown segmenter (vmap),
   not the per-chapter Word lists. en + Nepali; other languages fall back
   to English. Do not fabricate curriculum content — these are generic
   function words with well-established meanings.
   ============================================================ */
window.EXTRA_DICT = [
  { ko: "고르세요", en: "please choose", ne: "छान्नुहोस्" },
  { ko: "고르다", en: "to choose", ne: "छान्नु" },
  { ko: "알맞은", en: "suitable, appropriate", ne: "उपयुक्त" },
  { ko: "알맞다", en: "to be suitable", ne: "उपयुक्त हुनु" },
  { ko: "들어갈", en: "that goes in / fits", ne: "भर्ने, जाने" },
  { ko: "윗글의", en: "of the passage above", ne: "माथिको लेखको" },
  { ko: "윗글", en: "the passage above", ne: "माथिको लेख" },
  { ko: "것을", en: "the thing (object)", ne: "कुरालाई" },
  { ko: "내용과", en: "with the content", ne: "सामग्रीसँग" },
  { ko: "내용을", en: "the content (object)", ne: "सामग्रीलाई" },
  { ko: "내용으로", en: "as the content", ne: "सामग्रीको रूपमा" },
  { ko: "같으면", en: "if (it) is the same", ne: "उस्तै भए" },
  { ko: "다르면", en: "if (it) is different", ne: "फरक भए" },
  { ko: "맞으면", en: "if (it) is correct", ne: "सही भए" },
  { ko: "말을", en: "the word / speech (object)", ne: "शब्द, कुरा" },
  { ko: "보세요", en: "please look / try", ne: "हेर्नुहोस्, गर्नुहोस्" },
  { ko: "참이다", en: "is true", ne: "सत्य हो" },
  { ko: "빈칸", en: "blank space", ne: "खाली ठाउँ" },
  { ko: "채우세요", en: "please fill in", ne: "भर्नुहोस्" },
  { ko: "채우다", en: "to fill", ne: "भर्नु" },
  { ko: "옳은", en: "correct, right", ne: "सही" },
  { ko: "옳지", en: "(not) right", ne: "सही (होइन)" },
  { ko: "틀린", en: "wrong, incorrect", ne: "गलत" },
  { ko: "않은", en: "(that is) not (negation)", ne: "नभएको" },
  { ko: "완성해", en: "complete (and)", ne: "पूरा गरेर" },
  { ko: "완성하다", en: "to complete", ne: "पूरा गर्नु" },
  { ko: "연결해", en: "connect (and)", ne: "जोडेर" },
  { ko: "체크해", en: "check (and)", ne: "जाँच गरेर" },
  { ko: "중심", en: "center, focus", ne: "केन्द्र" },
  { ko: "있었다", en: "there was / had", ne: "थियो" },
  { ko: "꿈이", en: "dream (subject)", ne: "सपना" },
  { ko: "메모를", en: "memo (object)", ne: "मेमो, टिपोट" },
  { ko: "약속을", en: "appointment / promise (object)", ne: "भेटघाट, वाचा" },
  { ko: "잡아", en: "grab / make (and)", ne: "समातेर" },
  { ko: "잊어버려요", en: "forgets (completely)", ne: "बिर्सिन्छ" },
  { ko: "잊어버리다", en: "to forget", ne: "बिर्सिनु" },
  { ko: "세계에서", en: "in the world", ne: "संसारमा" },
  { ko: "마치는", en: "that finishes", ne: "सक्ने" },
  { ko: "맞히는", en: "that guesses right", ne: "ठीक पार्ने" },
  { ko: "여쭤보길", en: "to ask (humble)", ne: "सोध्न (आदरार्थी)" },
  { ko: "잘했네요", en: "did well", ne: "राम्रो गर्नुभयो" },
  { ko: "잠가", en: "lock (and)", ne: "ताल्चा लगाएर" },
  { ko: "잠그다", en: "to lock", ne: "ताल्चा लगाउनु" },
  { ko: "놓았어요", en: "have done (and left it)", ne: "गरेर राखेको छु" },
  { ko: "놓다", en: "to put / do in advance", ne: "गरेर राख्नु" },
  { ko: "예매해", en: "book / reserve (and)", ne: "बुकिङ गरेर" },
  { ko: "예매", en: "advance booking", ne: "अग्रिम बुकिङ" },
  { ko: "적어", en: "write down (and)", ne: "लेखेर" },
  { ko: "문을", en: "the door (object)", ne: "ढोका" },
  { ko: "살고", en: "live (and)", ne: "बसेर" },
  { ko: "싶은", en: "that (one) wants to", ne: "गर्न चाहेको" },
  { ko: "어떡하면", en: "what should (I) do", ne: "के गरे" },
  { ko: "좋을까요", en: "would it be good?", ne: "राम्रो होला?" },
  { ko: "잠이", en: "sleep (subject)", ne: "निद्रा" },
  { ko: "지키는", en: "that keeps / protects", ne: "पालना गर्ने" },
  { ko: "가까우면", en: "if (it is) close", ne: "नजिक भए" },
  { ko: "깨닫게", en: "to come to realize", ne: "महसुस गर्न" }
];
