# -*- coding: utf-8 -*-
import json, sys

LANGS = ["ne","bn","ru","he","ms","vi","id","si","pt","fr","ta"]

# (unique substring in korean key, [ne,bn,ru,he,ms,vi,id,si,pt,fr,ta])
items = [
("어떤 어려움이 있어요", ["तपाईंलाई कोरियन प्रयोग गर्दा कस्ता कठिनाइहरू हुन्छन्?","আপনি কোরিয়ান ব্যবহার করার সময় কী কী অসুবিধার সম্মুখীন হন?","С какими трудностями вы сталкиваетесь при использовании корейского языка?","אילו קשיים יש לכם כשאתם משתמשים בקוריאנית?","Apakah kesukaran yang anda hadapi ketika menggunakan bahasa Korea?","Bạn gặp những khó khăn gì khi sử dụng tiếng Hàn?","Kesulitan apa yang Anda alami saat menggunakan bahasa Korea?","ඔබ කොරියානු භාෂාව භාවිතා කරන විට ඔබට කුමන දුෂ්කරතා තිබේද?","Que dificuldades você tem ao usar o coreano?","Quelles difficultés rencontrez-vous en utilisant le coréen?","நீங்கள் கொரிய மொழியைப் பயன்படுத்தும்போது என்ன சிரமங்களை எதிர்கொள்கிறீர்கள்?"]),
("다른 사람과 말할 때 어떤 문제", ["तपाईं अरूसँग कुरा गर्दा कस्ता समस्याहरू हुन्छन्?","আপনি অন্যদের সাথে কথা বলার সময় কী কী সমস্যায় পড়েন?","Какие проблемы возникают у вас при разговоре с другими людьми?","אילו בעיות יש לכם כשאתם מדברים עם אנשים אחרים?","Apakah masalah yang anda hadapi ketika bercakap dengan orang lain?","Bạn gặp những vấn đề gì khi nói chuyện với người khác?","Masalah apa yang Anda alami saat berbicara dengan orang lain?","ඔබ වෙනත් අය සමඟ කතා කරන විට ඔබට කුමන ගැටලු තිබේද?","Que problemas você tem ao falar com outras pessoas?","Quels problèmes rencontrez-vous en parlant avec d'autres personnes?","நீங்கள் மற்றவர்களுடன் பேசும்போது என்ன பிரச்சினைகளை எதிர்கொள்கிறீர்கள்?"]),
("지루한 이야기를 할 때 어떻게", ["साथीले झर्को लाग्दो कुरा गर्दा तपाईं के गर्नुहुन्छ?","বন্ধু যখন বিরক্তিকর গল্প বলে তখন আপনি কী করেন?","Что вы делаете, когда друг рассказывает скучную историю?","מה אתם עושים כשחבר מספר סיפור משעמם?","Apa yang anda buat apabila kawan bercerita sesuatu yang membosankan?","Bạn làm gì khi bạn bè kể một câu chuyện nhàm chán?","Apa yang Anda lakukan saat teman bercerita hal yang membosankan?","යාළුවෙක් කම්මැලි කතාවක් කියන විට ඔබ කරන්නේ කුමක්ද?","O que você faz quando um amigo conta uma história chata?","Que faites-vous quand un ami raconte une histoire ennuyeuse?","ஒரு நண்பர் சலிப்பான கதையைச் சொல்லும்போது நீங்கள் என்ன செய்வீர்கள்?"]),
("의도하지 않았는데 일어난 일이 있어요", ["तपाईंले नचाहेको तर भइहालेको कुनै घटना छ?","আপনি চাননি কিন্তু ঘটে গেছে এমন কিছু কি হয়েছে?","Случалось ли с вами что-то, чего вы не хотели?","קרה לכם משהו שלא התכוונתם אליו?","Adakah pernah berlaku sesuatu yang anda tidak sengajakan?","Đã có việc gì xảy ra ngoài ý muốn của bạn chưa?","Pernahkah terjadi sesuatu yang tidak Anda inginkan?","ඔබ අදහස් නොකළ, නමුත් සිදු වූ දෙයක් තිබේද?","Já aconteceu algo que você não pretendia?","Vous est-il arrivé quelque chose que vous n'aviez pas voulu?","நீங்கள் நினைக்காத ஒன்று நடந்ததுண்டா?"]),
("나가기 싫어서 바쁜 척했어요", ["बाहिर जान मन नलागेर व्यस्त भएको बहाना गरें।","বাইরে যেতে চাইনি বলে ব্যস্ত থাকার ভান করলাম।","Мне не хотелось выходить, поэтому я сделал вид, что занят.","לא רציתי לצאת, אז העמדתי פנים שאני עסוק.","Saya tak mahu keluar, jadi saya berpura-pura sibuk.","Tôi không muốn ra ngoài nên đã giả vờ bận.","Saya tidak mau keluar, jadi saya pura-pura sibuk.","පිටතට යන්න අකමැති නිසා මම කාර්යබහුල බව මවා පෑවා.","Não queria sair, então fingi estar ocupado.","Je ne voulais pas sortir, alors j'ai fait semblant d'être occupé.","வெளியே போக விருப்பமில்லாததால் வேலையாக இருப்பது போல் நடித்தேன்."]),
("받기 싫은 전화를 받았을 때 바쁜 척", ["उठाउन मन नलाग्ने फोन आउँदा म व्यस्त भएको बहाना गर्छु।","যে ফোন ধরতে চাই না তা এলে ব্যস্ত থাকার ভান করি।","Когда поступает нежеланный звонок, я делаю вид, что занят.","כשמתקשרים אליי ואני לא רוצה לענות, אני מעמיד פנים שאני עסוק.","Apabila menerima panggilan yang tak mahu dijawab, saya berpura-pura sibuk.","Khi có cuộc gọi tôi không muốn nghe, tôi giả vờ bận.","Saat ada telepon yang tak ingin saya angkat, saya pura-pura sibuk.","ගන්න අකමැති ඇමතුමක් ආ විට මම කාර්යබහුල බව මවා පානවා.","Quando recebo uma ligação que não quero atender, finjo estar ocupado.","Quand je reçois un appel que je ne veux pas prendre, je fais semblant d'être occupé.","எடுக்க விருப்பமில்லாத அழைப்பு வரும்போது வேலையாக இருப்பது போல் நடிக்கிறேன்."]),
("처음 만난 사람들 앞에서 멋있는 척", ["पहिलो पटक भेटेका मानिसहरूअगाडि म सान्दार भएको बहाना गर्छु।","প্রথম দেখা মানুষদের সামনে আমি নিজেকে দারুণ দেখানোর ভান করি।","Перед людьми, которых вижу впервые, я притворяюсь крутым.","מול אנשים שאני פוגש בפעם הראשונה אני מעמיד פנים שאני מגניב.","Di hadapan orang yang baru dikenali, saya berpura-pura hebat.","Trước những người mới gặp lần đầu, tôi giả vờ tỏ ra ngầu.","Di depan orang yang baru pertama kali ditemui, saya pura-pura keren.","මුල් වරට හමු වූ අය ඉදිරියේ මම හොඳ බව මවා පානවා.","Diante de pessoas que conheço pela primeira vez, finjo ser descolado.","Devant des gens que je rencontre pour la première fois, je fais semblant d'être cool.","முதன்முதலில் சந்திக்கும் நபர்களுக்கு முன்பு நான் அருமையானவன் போல் நடிக்கிறேன்."]),
("일찍 일어나라고 하실 때 자는 척", ["आमाबुबाले चाँडै उठ भन्नुहुँदा म सुतिरहेको बहाना गर्छु।","বাবা-মা যখন তাড়াতাড়ি উঠতে বলেন, আমি ঘুমানোর ভান করি।","Когда родители велят рано вставать, я притворяюсь спящим.","כשההורים אומרים לי לקום מוקדם, אני מעמיד פנים שאני ישן.","Apabila ibu bapa menyuruh bangun awal, saya berpura-pura tidur.","Khi bố mẹ bảo dậy sớm, tôi giả vờ đang ngủ.","Saat orang tua menyuruh bangun pagi, saya pura-pura tidur.","දෙමව්පියන් උදෑසන අවදි වන්න කියන විට මම නිදාගෙන සිටින බව මවා පානවා.","Quando meus pais mandam eu acordar cedo, finjo estar dormindo.","Quand mes parents me disent de me lever tôt, je fais semblant de dormir.","பெற்றோர் அதிகாலையில் எழுந்திரு என்று சொல்லும்போது நான் தூங்குவது போல் நடிக்கிறேன்."]),
("광고 전화를 받았을 때 한국어를 전혀 못하는 척", ["विज्ञापन फोन आउँदा म कोरियन बिल्कुलै आउँदैन भन्ने बहाना गर्छु।","বিজ্ঞাপনের ফোন এলে আমি একদম কোরিয়ান পারি না এমন ভান করি।","Когда звонят с рекламой, я делаю вид, что совсем не говорю по-корейски.","כשמתקשרים אליי בשיחת פרסום, אני מעמיד פנים שאני בכלל לא יודע קוריאנית.","Apabila menerima panggilan iklan, saya berpura-pura langsung tidak tahu bahasa Korea.","Khi nhận cuộc gọi quảng cáo, tôi giả vờ hoàn toàn không biết tiếng Hàn.","Saat menerima telepon iklan, saya pura-pura sama sekali tidak bisa bahasa Korea.","වෙළඳ ප්‍රචාරක ඇමතුමක් ආ විට මම කොරියානු භාෂාව කිසිසේත් නොදන්නා බව මවා පානවා.","Quando recebo uma ligação de propaganda, finjo não saber nada de coreano.","Quand je reçois un appel publicitaire, je fais semblant de ne pas parler coréen du tout.","விளம்பர அழைப்பு வரும்போது எனக்கு கொரிய மொழியே தெரியாதது போல் நடிக்கிறேன்."]),
("말다툼한 사람을 길에서 만났을 때", ["झगडा गरेको मान्छेलाई बाटोमा भेट्दा म त्यसलाई नचिनेको बहाना गर्छु।","যার সাথে ঝগড়া হয়েছে তাকে রাস্তায় দেখলে আমি না চেনার ভান করি।","Встретив на улице человека, с которым поссорился, я делаю вид, что не знаю его.","כשאני פוגש ברחוב מישהו שרבתי איתו, אני מעמיד פנים שאני לא מכיר אותו.","Apabila terserempak di jalan dengan orang yang pernah bertengkar, saya berpura-pura tidak mengenalinya.","Khi gặp trên đường người từng cãi nhau, tôi giả vờ không quen họ.","Saat bertemu di jalan dengan orang yang pernah bertengkar, saya pura-pura tidak mengenalnya.","රණ්ඩු වූ පුද්ගලයෙක් පාරේදී හමු වූ විට මම ඔහුව නොදන්නා බව මවා පානවා.","Quando encontro na rua alguém com quem briguei, finjo não conhecê-lo.","Quand je croise dans la rue une personne avec qui je me suis disputé, je fais semblant de ne pas la connaître.","சண்டையிட்ட ஒருவரை தெருவில் சந்திக்கும்போது அவரை அறியாதது போல் நடிக்கிறேன்."]),
("고향의 가족들이 걱정할 때 별일 없이", ["गाउँघरका परिवारले चिन्ता गर्दा म कुनै समस्या नभई राम्रोसँग बाँचिरहेको बहाना गर्छु।","দেশের পরিবার যখন দুশ্চিন্তা করে, আমি কোনো সমস্যা ছাড়াই ভালো আছি এমন ভান করি।","Когда родные на родине волнуются, я делаю вид, что живу хорошо и без забот.","כשהמשפחה בבית דואגת, אני מעמיד פנים שאני חי טוב וללא בעיות.","Apabila keluarga di kampung bimbang, saya berpura-pura hidup baik tanpa masalah.","Khi gia đình ở quê lo lắng, tôi giả vờ sống tốt, không có chuyện gì.","Saat keluarga di kampung khawatir, saya pura-pura hidup baik tanpa masalah.","ගමේ පවුලේ අය කනස්සල්ලට පත් වන විට මම කිසි කරදරයක් නැතුව හොඳින් ජීවත් වන බව මවා පානවා.","Quando minha família na terra natal se preocupa, finjo que vivo bem, sem problemas.","Quand ma famille au pays s'inquiète, je fais semblant de bien vivre, sans souci.","சொந்த ஊர் குடும்பத்தினர் கவலைப்படும்போது எந்தப் பிரச்சினையும் இல்லாமல் நன்றாக வாழ்வது போல் நடிக்கிறேன்."]),
("이해가 안 됐지만 공감하는 척", ["साथीले भनेको कुरा बुझिनँ तर सहानुभूति देखाएको बहाना गरें।","বন্ধুর কথা বুঝিনি, তবু সহানুভূতি দেখানোর ভান করলাম।","Я не понял, что сказал друг, но сделал вид, что сочувствую.","לא הבנתי מה שחברי אמר, אבל העמדתי פנים שאני מזדהה.","Saya tidak faham apa yang kawan cakap, tetapi berpura-pura bersimpati.","Tôi không hiểu bạn nói gì nhưng vẫn giả vờ đồng cảm.","Saya tidak paham perkataan teman, tetapi pura-pura berempati.","යාළුවා කී දේ තේරුම් ගත්තේ නැහැ, නමුත් මම එකඟ වන බව මවා පෑවා.","Não entendi o que meu amigo disse, mas fingi ter empatia.","Je n'ai pas compris ce que mon ami disait, mais j'ai fait semblant de compatir.","நண்பர் சொன்னது புரியவில்லை, ஆனாலும் அனுதாபம் காட்டுவது போல் நடித்தேன்."]),
("너무 창피해서 안 아픈 척", ["बाटोमा लडें तर धेरै लाज लागेर दुखेको छैन भन्ने बहाना गरें।","রাস্তায় পড়ে গিয়েছিলাম, কিন্তু খুব লজ্জা পেয়ে ব্যথা পাইনি এমন ভান করলাম।","Я упал на улице, но от смущения сделал вид, что мне не больно.","נפלתי ברחוב, אבל כל כך התביישתי שהעמדתי פנים שלא כואב לי.","Saya jatuh di jalan, tetapi terlalu malu sehingga berpura-pura tidak sakit.","Tôi ngã trên đường nhưng xấu hổ quá nên giả vờ không đau.","Saya jatuh di jalan, tetapi karena malu saya pura-pura tidak sakit.","පාරේදී ඇද වැටුණා, නමුත් ලැජ්ජාව නිසා රිදෙන්නේ නැති බව මවා පෑවා.","Caí na rua, mas de tão envergonhado fingi que não doía.","Je suis tombé dans la rue, mais j'avais tellement honte que j'ai fait semblant de ne pas avoir mal.","தெருவில் விழுந்தேன், ஆனால் மிகவும் வெட்கப்பட்டதால் வலிக்கவில்லை போல் நடித்தேன்."]),
("모국어를 섞어 써요", ["हतार भयो भने म मातृभाषा मिसाएर बोल्छु।","তাড়া থাকলে আমি মাতৃভাষা মিশিয়ে বলি।","Когда тороплюсь, я примешиваю родной язык.","כשאני ממהר, אני מערבב את שפת האם שלי.","Apabila tergesa-gesa, saya mencampurkan bahasa ibunda.","Khi vội, tôi pha lẫn tiếng mẹ đẻ vào.","Saat terburu-buru, saya mencampur bahasa ibu.","හදිසි වූ විට මම මව් භාෂාව මිශ්‍ර කර කතා කරනවා.","Quando estou com pressa, misturo minha língua materna.","Quand je suis pressé, je mélange ma langue maternelle.","அவசரமாக இருக்கும்போது நான் தாய்மொழியைக் கலந்து பேசுகிறேன்."]),
("잠시드 씨와 안젤라 씨가 이야기합니다", ["जमसिद र एन्जेला कुराकानी गर्दै छन्।","জামসিদ ও অ্যাঞ্জেলা কথা বলছেন।","Джамшид и Анджела разговаривают.","ג'מסיד ואנג'לה משוחחים.","Encik Jamsid dan Cik Angela sedang berbual.","Anh Jamsid và chị Angela đang trò chuyện.","Jamsid dan Angela sedang berbicara.","ජම්සිඩ් සහ ඇන්ජෙලා කතා කරති.","Jamsid e Angela estão conversando.","Jamsid et Angela discutent.","ஜம்சித்தும் ஏஞ்சலாவும் பேசிக்கொண்டிருக்கிறார்கள்."]),
("회의 준비를 열심히 하지 않았다", ["एन्जेलाले बैठकको तयारी मेहनतका साथ गरिनन्।","অ্যাঞ্জেলা মিটিংয়ের জন্য মন দিয়ে প্রস্তুতি নেননি।","Анджела не готовилась усердно к совещанию.","אנג'לה לא התכוננה ברצינות לפגישה.","Angela tidak bersungguh-sungguh menyediakan mesyuarat.","Angela đã không chuẩn bị kỹ cho cuộc họp.","Angela tidak sungguh-sungguh menyiapkan rapat.","ඇන්ජෙලා රැස්වීමට හොඳින් සූදානම් වුණේ නැහැ.","Angela não se preparou com afinco para a reunião.","Angela ne s'est pas préparée sérieusement à la réunion.","ஏஞ்சலா கூட்டத்திற்கு கடுமையாகத் தயாராகவில்லை."]),
("거래처 사람들이 좀 불쾌해하는 것 같았다", ["ग्राहक कम्पनीका मानिसहरू केही असन्तुष्ट देखिन्थे।","ক্লায়েন্ট প্রতিষ্ঠানের লোকজন কিছুটা অসন্তুষ্ট মনে হচ্ছিল।","Люди из компании-партнёра выглядели немного недовольными.","נראה שאנשי הלקוח היו קצת לא מרוצים.","Orang dari syarikat pelanggan kelihatan agak tidak berpuas hati.","Những người bên đối tác có vẻ hơi khó chịu.","Orang-orang dari perusahaan mitra tampak agak tidak senang.","ගනුදෙනුකරු සමාගමේ අය ටිකක් අප්‍රසන්න බවක් පෙනුණා.","As pessoas da empresa cliente pareciam um pouco descontentes.","Les gens de l'entreprise cliente semblaient un peu mécontents.","வாடிக்கையாளர் நிறுவனத்தினர் சற்று அதிருப்தியாக இருந்ததாகத் தோன்றியது."]),
("회의에서 자신의 의견을 어떻게 말했습니까", ["एन्जेलाले बैठकमा आफ्नो विचार कसरी व्यक्त गरिन्?","অ্যাঞ্জেলা মিটিংয়ে নিজের মতামত কীভাবে প্রকাশ করলেন?","Как Анджела выразила своё мнение на совещании?","כיצד אנג'לה הביעה את דעתה בפגישה?","Bagaimanakah Angela menyampaikan pendapatnya dalam mesyuarat?","Angela đã bày tỏ ý kiến của mình trong cuộc họp như thế nào?","Bagaimana Angela menyampaikan pendapatnya dalam rapat?","ඇන්ජෙලා රැස්වීමේදී තම අදහස ප්‍රකාශ කළේ කෙසේද?","Como Angela expressou a sua opinião na reunião?","Comment Angela a-t-elle exprimé son opinion lors de la réunion?","ஏஞ்சலா கூட்டத்தில் தன் கருத்தை எப்படி வெளிப்படுத்தினார்?"]),
("참으려고 했지만 결국 야식을 먹고 말았어요", ["सहन खोजें तर अन्ततः राति खाजा खाइहालें।","সংযত থাকার চেষ্টা করেছিলাম, কিন্তু শেষমেশ রাতের খাবার খেয়ে ফেললাম।","Я пытался удержаться, но в итоге всё же поел на ночь.","ניסיתי להתאפק, אבל בסוף אכלתי חטיף לילה.","Saya cuba menahan diri, tetapi akhirnya makan juga snek tengah malam.","Tôi đã cố nhịn nhưng cuối cùng vẫn ăn khuya.","Saya berusaha menahan diri, tetapi akhirnya tetap makan camilan malam.","මම ඉවසන්න උත්සාහ කළත් අන්තිමට රෑ කෑම කාලා දැම්මා.","Tentei me segurar, mas acabei comendo um lanche noturno.","J'ai essayé de me retenir, mais j'ai fini par manger un en-cas nocturne.","பொறுத்துக்கொள்ள முயற்சித்தேன், ஆனால் இறுதியில் இரவு உணவை சாப்பிட்டேவிட்டேன்."]),
("너무 긴장해서 아는 문제도 틀리고 말았어요", ["धेरै तनावमा परेर थाहा भएको प्रश्न पनि गलत गरिहालें।","খুব নার্ভাস হয়ে জানা প্রশ্নও ভুল করে ফেললাম।","Я так нервничал, что ошибся даже в тех вопросах, которые знал.","הייתי כל כך לחוץ שטעיתי אפילו בשאלות שידעתי.","Saya terlalu gugup sehingga tersalah menjawab soalan yang saya tahu.","Tôi quá hồi hộp nên làm sai cả những câu tôi biết.","Saya terlalu gugup sampai salah menjawab soal yang saya tahu.","මම ඉතා කලබල වුණ නිසා දන්න ප්‍රශ්නත් වැරදුණා.","Fiquei tão nervoso que errei até as questões que sabia.","J'étais si stressé que je me suis trompé même sur les questions que je connaissais.","மிகவும் பதற்றமடைந்ததால் தெரிந்த கேள்விகளையும் தவறாக எழுதிவிட்டேன்."]),
("청소기를 돌리다가 발을 헛디뎌서 넘어지고 말았어요", ["भ्याकुम चलाउँदै गर्दा खुट्टा चिप्लिएर लडिहालें।","ভ্যাকুয়াম ক্লিনার চালাতে গিয়ে পা পিছলে পড়ে গেলাম।","Пылесося, я оступился и упал.","תוך כדי שאיבת אבק, מעדתי ונפלתי.","Semasa menggunakan pembersih vakum, saya tersalah pijak lalu terjatuh.","Trong lúc hút bụi, tôi hụt chân và ngã.","Saat menyedot debu, saya salah langkah lalu terjatuh.","වැක්යුම් යන්ත්‍රය පාවිච්චි කරමින් සිටියදී පය පැටලී ඇද වැටුණා.","Enquanto passava o aspirador, tropecei e acabei caindo.","En passant l'aspirateur, j'ai fait un faux pas et je suis tombé.","வாக்யூம் கிளீனரைப் பயன்படுத்தும்போது கால் தடுமாறி விழுந்துவிட்டேன்."]),
("제 발음이 부정확해서 사람들이 잘못 알아듣고 말았어요", ["मेरो उच्चारण अशुद्ध भएकाले मानिसहरूले गलत बुझिहाले।","আমার উচ্চারণ ভুল হওয়ায় লোকজন ভুল বুঝে ফেলল।","Из-за моего неточного произношения люди меня неправильно поняли.","ההגייה שלי הייתה לא מדויקת, אז אנשים הבינו לא נכון.","Sebutan saya tidak tepat, jadi orang tersalah faham.","Phát âm của tôi không chuẩn nên mọi người đã hiểu nhầm.","Pengucapan saya kurang tepat, sehingga orang salah paham.","මගේ උච්චාරණය නිවැරදි නොවූ නිසා අය වැරදියට තේරුම් ගත්තා.","Minha pronúncia estava incorreta, então as pessoas entenderam errado.","Ma prononciation était incorrecte, alors les gens ont mal compris.","என் உச்சரிப்பு சரியில்லாததால் மக்கள் தவறாகப் புரிந்துகொண்டனர்."]),
("지도 마침 출발하려던 참이었어요", ["म पनि भर्खरै निस्कन लाग्दै थिएँ।","আমিও ঠিক তখনই রওনা দিতে যাচ্ছিলাম।","Я как раз тоже собирался выходить.","גם אני בדיוק עמדתי לצאת.","Saya pun kebetulan baru hendak bertolak.","Tôi cũng vừa định xuất phát.","Saya pun kebetulan baru mau berangkat.","මමත් හරියටම පිටත් වෙන්න යන්න හිටියේ.","Eu também estava justamente prestes a sair.","Moi aussi, j'étais justement sur le point de partir.","நானும் சரியாக கிளம்பப் போகிறவனாக இருந்தேன்."]),
("보기와 같이 친구와 이야기해 보세요", ["उदाहरणमा जस्तै साथीसँग कुरा गर्नुहोस्।","উদাহরণের মতো করে বন্ধুর সাথে কথা বলুন।","Поговорите с другом, как в примере.","שוחחו עם חבר כמו בדוגמה.","Berbuallah dengan kawan seperti dalam contoh.","Hãy nói chuyện với bạn như trong ví dụ.","Berbicaralah dengan teman seperti pada contoh.","උදාහරණයේ මෙන් යාළුවා සමඟ කතා කර බලන්න.","Converse com um amigo como no exemplo.","Parlez avec un ami comme dans l'exemple.","எடுத்துக்காட்டில் உள்ளதைப் போல் நண்பருடன் பேசிப் பாருங்கள்."]),
("아이의 교복을 물려발으면 풀아요", ["छिमेकीबाट बच्चाको स्कुल पोशाक सरुवा गरेर पाए राम्रो हुन्छ।","প্রতিবেশীর কাছ থেকে বাচ্চার স্কুল ইউনিফর্ম হাতে পেলে ভালো হয়।","Хорошо, если получить детскую школьную форму от соседа.","זה נחמד לקבל את מדי בית הספר של הילד בירושה משכן.","Baik juga jika mewarisi pakaian seragam sekolah anak daripada jiran.","Nếu được hàng xóm để lại đồng phục học sinh cho con thì thật tốt.","Akan baik jika mendapat seragam sekolah anak dari tetangga.","අසල්වැසියාගෙන් දරුවාගේ පාසල් නිල ඇඳුම උරුම කර ගත්තොත් හොඳයි.","É bom receber o uniforme escolar da criança de um vizinho.","C'est bien de récupérer l'uniforme scolaire de l'enfant d'un voisin.","அண்டை வீட்டாரிடமிருந்து குழந்தையின் பள்ளி சீருடையைப் பெற்றால் நல்லது."]),
("이링 씨 한국어가 유창해서 항상 부러웠는데요", ["इलिङको कोरियन प्रवाहमय भएकाले म सधैँ ईर्ष्या गर्थें।","ইলিং-এর কোরিয়ান সাবলীল হওয়ায় আমি সবসময় ঈর্ষা করতাম।","Я всегда завидовал Илин, ведь она свободно говорит по-корейски.","תמיד קינאתי באילינג כי הקוריאנית שלה שוטפת.","Saya sentiasa cemburu kerana bahasa Korea Iling sangat fasih.","Tôi luôn ganh tị vì tiếng Hàn của Iling rất trôi chảy.","Saya selalu iri karena bahasa Korea Iling sangat lancar.","ඉලිංගේ කොරියානු භාෂාව චතුර නිසා මම හැමවිටම ඊර්ෂ්‍යා කළා.","Sempre invejei a Iling porque o coreano dela é fluente.","J'ai toujours envié Iling car son coréen est courant.","இலிங்கின் கொரிய மொழி சரளமாக இருப்பதால் நான் எப்போதும் பொறாமைப்பட்டேன்."]),
("단어가 잘 안 떠오를 때가 많고 마음이 급하면 모국어를 섞어 쓰기도 해요", ["शब्द नआउने बेला धेरै हुन्छ, र हतार भयो भने मातृभाषा मिसाएर पनि बोल्छु।","প্রায়ই শব্দ মনে আসে না, আর তাড়া থাকলে মাতৃভাষা মিশিয়েও বলি।","Часто слова не приходят на ум, а когда тороплюсь, даже примешиваю родной язык.","לעיתים קרובות מילים לא עולות לי לראש, וכשאני ממהר אני אפילו מערבב את שפת האם.","Selalu perkataan tidak terlintas, dan apabila tergesa-gesa saya turut mencampurkan bahasa ibunda.","Nhiều khi từ ngữ không nghĩ ra được, và khi vội tôi còn pha lẫn tiếng mẹ đẻ.","Sering kata-kata tidak terpikir, dan saat terburu-buru saya bahkan mencampur bahasa ibu.","වචන මතක් නොවන අවස්ථා බොහෝ වන අතර, හදිසි වූ විට මව් භාෂාවත් මිශ්‍ර කර භාවිතා කරනවා.","Muitas vezes as palavras não me vêm à cabeça e, com pressa, até misturo minha língua materna.","Souvent les mots ne me viennent pas, et quand je suis pressé je mélange même ma langue maternelle.","அடிக்கடி வார்த்தைகள் நினைவுக்கு வராது, அவசரத்தில் தாய்மொழியையும் கலந்து பயன்படுத்துகிறேன்."]),
("신조어나 유행어를 따라 하고 싶은데 너무 빨리 바뀐다", ["नयाँ शब्द वा प्रचलित शब्द पछ्याउन मन लाग्छ तर धेरै छिटो बदलिन्छ।","নতুন শব্দ বা চলতি স্ল্যাং অনুসরণ করতে চাই, কিন্তু সেগুলো খুব দ্রুত বদলে যায়।","Хочется поспевать за неологизмами и модными словечками, но они меняются слишком быстро.","אני רוצה לעקוב אחרי מילים חדשות וסלנג, אבל הם משתנים מהר מדי.","Saya mahu mengikuti kata baharu atau bahasa trend, tetapi ia berubah terlalu cepat.","Tôi muốn bắt kịp từ mới và tiếng lóng, nhưng chúng thay đổi quá nhanh.","Saya ingin mengikuti kata baru atau bahasa gaul, tetapi berubah terlalu cepat.","නව වචන හෝ ප්‍රචලිත වචන අනුගමනය කරන්න කැමතියි, නමුත් ඒවා ඉතා ඉක්මනින් වෙනස් වෙනවා.","Quero acompanhar os neologismos e as gírias, mas eles mudam rápido demais.","Je veux suivre les néologismes et l'argot, mais ils changent trop vite.","புதிய சொற்களையும் நடைமுறை வழக்குச் சொற்களையும் பின்பற்ற விரும்புகிறேன், ஆனால் அவை மிக விரைவாக மாறுகின்றன."]),
("언어생활을 위해 지켜야 할 것은 무엇일까요", ["सही भाषिक व्यवहारका लागि पालना गर्नुपर्ने कुरा के हो?","সঠিক ভাষা ব্যবহারের জন্য আমাদের কী মেনে চলা উচিত?","Что нужно соблюдать для правильного использования языка?","מה עלינו לשמור כדי לקיים שימוש נכון בשפה?","Apakah yang perlu kita patuhi untuk penggunaan bahasa yang betul?","Để sử dụng ngôn ngữ đúng đắn, chúng ta cần tuân thủ điều gì?","Apa yang harus kita patuhi untuk penggunaan bahasa yang benar?","නිසි භාෂා භාවිතය සඳහා අප පිළිපැදිය යුත්තේ කුමක්ද?","O que devemos observar para um uso correto da língua?","Que devons-nous respecter pour un bon usage de la langue?","சரியான மொழி பயன்பாட்டிற்கு நாம் கடைப்பிடிக்க வேண்டியது என்ன?"]),
("높임말이 헷갈려서 과장님께 반말을 하다", ["आदरार्थी भाषा अलमल भएर म्यानेजरलाई अनादरको भाषामा बोल्नु।","সম্মানসূচক ভাষা গুলিয়ে ফেলে ম্যানেজারের সাথে তুচ্ছার্থক ভাষায় কথা বলা।","заговорить с начальником на «ты», запутавшись в вежливой речи.","לדבר אל המנהל בלשון לא רשמית בגלל בלבול בלשון הכבוד.","bercakap secara tidak formal kepada ketua kerana keliru dengan bahasa hormat.","nói trống không với trưởng phòng vì bối rối với kính ngữ.","berbicara tidak sopan kepada manajer karena bingung dengan bahasa hormat.","ගෞරව වචන ව්‍යාකූල වීම නිසා කළමනාකරුට අගෞරව ලෙස කතා කිරීම.","falar informalmente com o chefe por se confundir com a linguagem honorífica.","parler de façon familière au chef de service parce qu'on confond le langage honorifique.","மரியாதைச் சொற்கள் குழப்பமாக இருந்ததால் மேலாளரிடம் மரியாதையின்றி பேசுவது."]),
("뜻을 잘못 알고 비속어를 사용하다", ["अर्थ गलत बुझेर अश्लील/खराब शब्द प्रयोग गर्नु।","অর্থ ভুল বুঝে অশালীন শব্দ ব্যবহার করা।","употреблять грубые слова, неправильно поняв их значение.","להשתמש במילות סלנג גסות מתוך הבנה שגויה של משמעותן.","menggunakan perkataan kesat kerana salah faham maksudnya.","dùng từ thô tục vì hiểu sai nghĩa.","menggunakan kata kasar karena salah memahami artinya.","අර්ථය වැරදියට තේරුම් ගෙන අශිෂ්ට වචන භාවිතා කිරීම.","usar palavrões por entender mal o significado.","employer des mots grossiers en comprenant mal leur sens.","பொருளைத் தவறாகப் புரிந்துகொண்டு கொச்சையான சொற்களைப் பயன்படுத்துவது."]),
("적절한 호칭을 몰라서 거래처 사람들을 잘못 부르다", ["उपयुक्त सम्बोधन थाहा नभएर ग्राहक कम्पनीका मानिसहरूलाई गलत तरिकाले सम्बोधन गर्नु।","উপযুক্ত সম্বোধন না জানায় ক্লায়েন্ট প্রতিষ্ঠানের লোকদের ভুলভাবে সম্বোধন করা।","неправильно обращаться к деловым партнёрам, не зная подходящего обращения.","לפנות בצורה שגויה לאנשי הלקוח מכיוון שלא יודעים את התואר המתאים.","memanggil orang syarikat pelanggan dengan salah kerana tidak tahu panggilan yang sesuai.","gọi sai những người bên đối tác vì không biết cách xưng hô phù hợp.","menyapa orang perusahaan mitra dengan salah karena tidak tahu sebutan yang tepat.","සුදුසු ආමන්ත්‍රණය නොදැන ගනුදෙනුකරු සමාගමේ අයට වැරදියට ආමන්ත්‍රණය කිරීම.","dirigir-se incorretamente às pessoas da empresa cliente por não saber o tratamento adequado.","s'adresser de façon incorrecte aux personnes de l'entreprise cliente faute de connaître le bon titre.","பொருத்தமான அழைப்புமுறை தெரியாததால் வாடிக்கையாளர் நிறுவனத்தினரை தவறாக அழைப்பது."]),
]

# load all missing korean keys
keys = []
with open("_all_missing.txt", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if " :: " not in line: continue
        keys.append(line.split(" :: ")[0])

batch = {}
skipped = []
for sub, trans in items:
    matches = [k for k in keys if sub in k]
    if len(matches) != 1:
        skipped.append((sub, len(matches)))
        continue
    key = matches[0]
    batch[key] = {LANGS[i]: trans[i] for i in range(len(LANGS))}

with open("_batch.json", "w", encoding="utf-8") as f:
    json.dump(batch, f, ensure_ascii=False, indent=1)

print("built:", len(batch), "items")
for s,n in skipped:
    print("SKIPPED (matches=%d):"%n, s)
