const fs=require("fs");
const list=require("./_cleanmiss.json");
// ne-only items: [substr, ne]
const NE=[
["라흐만: 그때는 새로운 환경에 적응하느라고 공부를 시작할 수 없었어요.","रहमान: त्यतिबेला नयाँ वातावरणमा अभ्यस्त हुनमै लागेर पढाइ सुरु गर्न सक्दिनथेँ।"],
["항상 음식을 조금씩 사요?","के तपाईं सधैं थोरै थोरै गरेर खानेकुरा किन्नुहुन्छ?"],
["명절에 음식을 많이 준비해요?","के तपाईं चाडपर्वमा धेरै खानेकुरा तयार गर्नुहुन्छ?"],
["다른 방법이 없어서 할 수밖에 없는 일에 대해 친구와 이야기해 보세요.","अरू कुनै उपाय नभएर गर्नैपर्ने कामको बारेमा साथीसँग कुरा गर्नुहोस्।"],
["저는 공부를 더 하고 싶지만 돈을 벌어야 해서 취직할 수밖에 없어요.","म अझै धेरै पढ्न चाहन्छु तर पैसा कमाउनुपर्ने भएकाले जागिर खानै बाध्य छु।"],
["부모님이 한국에 안 계셔서 명절에 혼자 보낼 수밖에 없어요.","आमाबुबा कोरियामा नहुनुभएकाले चाडपर्व एक्लै बिताउनुबाहेक अर्को उपाय छैन।"],
["한국어를 잘 못해서 한국 친구를 사귀기 힘들 수밖에 없어요.","कोरियन भाषा राम्ररी नआउने भएकाले कोरियन साथी बनाउन गाह्रो हुनु स्वाभाविकै हो।"],
["비자 때문에 일을 그만둘 수밖에 없었어요.","भिसाका कारण काम छोड्नुबाहेक अर्को विकल्प थिएन।"],
["후엔: 요즘 우리 세 식구는 분가 준비하느라 좀 바빠요.","हुएन: आजकल हामी तीन जनाको परिवार अलग बस्ने तयारीमा अलिकति व्यस्त छौं।"],
["후엔: 저도 그게 걱정이에요.","हुएन: मलाई पनि त्यसैको चिन्ता छ।"],
["한국에 오기 전에 한국에 대해서 어떻게 알고 있었어요?","कोरिया आउनुअघि तपाईंलाई कोरियाको बारेमा कस्तो थाहा थियो?"],
["④ 많을 뿐만 아니라","धेरै हुनु मात्र होइन"],
["③ 아름다웠는지 몰라요","कति सुन्दर थियो कुन्नि"],
["② 제출하는 줄 알았어요","बुझाउनुपर्छ भन्ठानेको थिएँ"],
["① 개인 정보 유출","व्यक्तिगत जानकारी चुहावट"]
];
// full-11 items: [substr, {lang:val}]
const FULL=[
["양파, 당근은 작게 깍둑썰기를 한다",{ne:"प्याज र गाजरलाई साना डल्ला (क्युब) मा काट्नुहोस्।",bn:"পেঁয়াজ ও গাজর ছোট ছোট কিউব করে কাটুন।",ru:"Лук и морковь нарежьте мелкими кубиками.",he:"חותכים את הבצל והגזר לקוביות קטנות.",ms:"Potong bawang dan lobak merah menjadi dadu kecil.",vi:"Cắt hành tây và cà rốt thành hạt lựu nhỏ.",id:"Potong bawang bombai dan wortel menjadi dadu kecil.",si:"ලූනු සහ කැරට් කුඩා කැට ලෙස කපන්න.",pt:"Corte a cebola e a cenoura em cubos pequenos.",fr:"Coupez l'oignon et la carotte en petits dés.",ta:"வெங்காயம் மற்றும் கேரட்டை சிறிய கனச்சதுரங்களாக நறுக்கவும்."}],
["돼지고기를 먼저 볶는다",{ne:"प्यानमा खानेतेल हालेर पहिले सुँगुरको मासु भुट्नुहोस्।",bn:"ফ্রাইং প্যানে তেল দিয়ে প্রথমে শুকরের মাংস ভাজুন।",ru:"Налейте в сковороду масло и сначала обжарьте свинину.",he:"מורחים שמן במחבת ומטגנים תחילה את בשר החזיר.",ms:"Panaskan minyak di kuali dan tumis daging babi terlebih dahulu.",vi:"Cho dầu ăn vào chảo và xào thịt lợn trước.",id:"Tuang minyak goreng ke wajan dan tumis daging babi terlebih dahulu.",si:"ෆ්‍රයිං පෑන් එකට තෙල් දමා මුලින්ම ඌරු මස් බැදගන්න.",pt:"Coloque óleo na frigideira e refogue primeiro a carne de porco.",fr:"Versez de l'huile dans la poêle et faites d'abord revenir le porc.",ta:"வாணலியில் எண்ணெய் ஊற்றி முதலில் பன்றி இறைச்சியை வதக்கவும்."}],
["돼지고기를 볶은 후 양파, 당근을 넣고 볶는다",{ne:"सुँगुरको मासु भुटेपछि प्याज र गाजर हालेर भुट्नुहोस्।",bn:"শুকরের মাংস ভাজার পর পেঁয়াজ ও গাজর দিয়ে ভাজুন।",ru:"Обжарив свинину, добавьте лук и морковь и обжарьте.",he:"לאחר טיגון בשר החזיר, מוסיפים בצל וגזר ומטגנים.",ms:"Selepas menumis daging babi, masukkan bawang dan lobak merah lalu tumis.",vi:"Sau khi xào thịt lợn, cho hành tây và cà rốt vào xào.",id:"Setelah menumis daging babi, masukkan bawang bombai dan wortel lalu tumis.",si:"ඌරු මස් බැදගත් පසු ලූනු සහ කැරට් දමා බැදගන්න.",pt:"Depois de refogar a carne de porco, acrescente a cebola e a cenoura e refogue.",fr:"Après avoir fait revenir le porc, ajoutez l'oignon et la carotte et faites sauter.",ta:"பன்றி இறைச்சியை வதக்கிய பிறகு வெங்காயம், கேரட் சேர்த்து வதக்கவும்."}],
["참기름, 깨를 뿌린다",{ne:"तिलको तेल र तिल छर्नुहोस्।",bn:"তিলের তেল ও তিল ছিটিয়ে দিন।",ru:"Посыпьте кунжутным маслом и семенами кунжута.",he:"מזלפים שמן שומשום ומפזרים שומשום.",ms:"Renjiskan minyak bijan dan biji bijan.",vi:"Rưới dầu mè và rắc mè lên.",id:"Taburkan minyak wijen dan biji wijen.",si:"තල තෙල් සහ තල ඉස්න්න.",pt:"Regue com óleo de gergelim e salpique sementes de gergelim.",fr:"Versez de l'huile de sésame et parsemez de graines de sésame.",ta:"எள் எண்ணெய் மற்றும் எள்ளைத் தூவவும்."}],
["맛있는 볶음밥 완성",{ne:"मिठो भुटेको भात तयार!",bn:"সুস্বাদু ফ্রাইড রাইস তৈরি!",ru:"Вкусный жареный рис готов!",he:"אורז מטוגן טעים מוכן!",ms:"Nasi goreng yang sedap siap!",vi:"Cơm chiên ngon đã hoàn thành!",id:"Nasi goreng lezat siap!",si:"රසවත් ෆ්‍රයිඩ් රයිස් සම්පූර්ණයි!",pt:"Arroz frito delicioso pronto!",fr:"Le délicieux riz sauté est prêt !",ta:"சுவையான ஃப்ரைடு ரைஸ் தயார்!"}],
["요리 방법 순서대로 번호를 써 보세요",{ne:"पकाउने विधिको क्रमअनुसार नम्बर लेख्नुहोस्।",bn:"রান্নার পদ্ধতির ক্রম অনুযায়ী নম্বর লিখুন।",ru:"Напишите номера по порядку способа приготовления.",he:"כתבו את המספרים לפי סדר שלבי ההכנה.",ms:"Tuliskan nombor mengikut urutan cara memasak.",vi:"Hãy viết số theo thứ tự cách nấu ăn.",id:"Tulislah nomor sesuai urutan cara memasak.",si:"උයන ක්‍රමයේ පිළිවෙළට අංක ලියන්න.",pt:"Escreva os números na ordem do modo de preparo.",fr:"Écrivez les numéros dans l'ordre des étapes de la recette.",ta:"சமையல் முறையின் வரிசைப்படி எண்களை எழுதுங்கள்."}],
["쌀을 씻어서 밥솥에 넣고 밥을 짓는다",{ne:"चामल धोएर राइस कुकरमा हालेर भात पकाउनुहोस्।",bn:"চাল ধুয়ে রাইস কুকারে দিয়ে ভাত রান্না করুন।",ru:"Промойте рис, положите в рисоварку и приготовьте.",he:"שוטפים את האורז, מכניסים לסיר האורז ומבשלים.",ms:"Basuh beras, masukkan ke dalam periuk nasi dan masak nasi.",vi:"Vo gạo, cho vào nồi cơm điện và nấu cơm.",id:"Cuci beras, masukkan ke penanak nasi, lalu masak nasi.",si:"සහල් සෝදා රයිස් කුකරයට දමා බත් උයන්න.",pt:"Lave o arroz, coloque na panela de arroz e cozinhe.",fr:"Rincez le riz, mettez-le dans le cuiseur et faites cuire.",ta:"அரிசியைக் கழுவி அரிசி குக்கரில் போட்டு சாதம் சமைக்கவும்."}],
["렌틸콩을 물에 불려서 냄비에 넣고 삶는다",{ne:"दाललाई पानीमा भिजाएर भाँडोमा हालेर उमाल्नुहोस्।",bn:"মসুর ডাল পানিতে ভিজিয়ে হাঁড়িতে দিয়ে সিদ্ধ করুন।",ru:"Замочите чечевицу в воде, положите в кастрюлю и отварите.",he:"משרים את העדשים במים, מכניסים לסיר ומבשלים.",ms:"Rendam kacang lentil dalam air, masukkan ke dalam periuk dan rebus.",vi:"Ngâm đậu lăng vào nước, cho vào nồi và luộc.",id:"Rendam kacang lentil dalam air, masukkan ke panci, lalu rebus.",si:"පරිප්පු වතුරේ පොඟවා හැළියට දමා තම්බන්න.",pt:"Deixe as lentilhas de molho, coloque numa panela e cozinhe.",fr:"Faites tremper les lentilles, mettez-les dans une casserole et faites bouillir.",ta:"பருப்பை தண்ணீரில் ஊறவைத்து பானையில் போட்டு வேகவைக்கவும்."}],
["팬에 기름을 두르고 양파, 마늘, 생강을 볶는다",{ne:"प्यानमा तेल हालेर प्याज, लसुन र अदुवा भुट्नुहोस्।",bn:"প্যানে তেল দিয়ে পেঁয়াজ, রসুন ও আদা ভাজুন।",ru:"Налейте в сковороду масло и обжарьте лук, чеснок и имбирь.",he:"מורחים שמן במחבת ומטגנים בצל, שום וג'ינג'ר.",ms:"Panaskan minyak di kuali dan tumis bawang, bawang putih dan halia.",vi:"Cho dầu vào chảo và xào hành tây, tỏi, gừng.",id:"Tuang minyak ke wajan dan tumis bawang bombai, bawang putih, dan jahe.",si:"පෑන් එකට තෙල් දමා ලූනු, සුදුලූනු සහ ඉඟුරු බැදගන්න.",pt:"Coloque óleo na frigideira e refogue cebola, alho e gengibre.",fr:"Versez de l'huile dans la poêle et faites revenir l'oignon, l'ail et le gingembre.",ta:"வாணலியில் எண்ணெய் ஊற்றி வெங்காயம், பூண்டு, இஞ்சி வதக்கவும்."}],
["내가 좋아하는 음식은 달밥이에요",{ne:"मलाई मन पर्ने खाना दालभात हो।",bn:"আমার প্রিয় খাবার হলো ডাল-ভাত।",ru:"Моё любимое блюдо — дал-бхат.",he:"המאכל האהוב עליי הוא דאל בהאט.",ms:"Makanan kegemaran saya ialah dal bhat.",vi:"Món ăn tôi yêu thích là dal bhat.",id:"Makanan favorit saya adalah dal bhat.",si:"මම වඩාත් කැමති කෑම දාල් බත්.",pt:"Minha comida favorita é o dal bhat.",fr:"Mon plat préféré est le dal bhat.",ta:"எனக்குப் பிடித்த உணவு தால் பாத்."}],
["재료는 쌀, 렌틸콩, 향신료가 필요해요",{ne:"सामग्रीमा चामल, दाल र मसला चाहिन्छ।",bn:"উপকরণ হিসেবে চাল, মসুর ডাল ও মসলা লাগে।",ru:"Из ингредиентов нужны рис, чечевица и специи.",he:"כמרכיבים דרושים אורז, עדשים ותבלינים.",ms:"Bahan yang diperlukan ialah beras, kacang lentil dan rempah.",vi:"Nguyên liệu cần có gạo, đậu lăng và gia vị.",id:"Bahan yang diperlukan adalah beras, kacang lentil, dan bumbu.",si:"අමුද්‍රව්‍ය ලෙස සහල්, පරිප්පු සහ කුළුබඩු අවශ්‍යයි.",pt:"Como ingredientes, são necessários arroz, lentilhas e temperos.",fr:"Comme ingrédients, il faut du riz, des lentilles et des épices.",ta:"பொருட்களாக அரிசி, பருப்பு, மசாலா தேவை."}],
["'유통 기한'은 무엇을 말합니까?",{ne:"'वितरण म्याद' भनेको के हो?",bn:"'বিক্রয়ের মেয়াদ' বলতে কী বোঝায়?",ru:"Что означает «срок реализации»?",he:"מהו 'תאריך אחרון למכירה'?",ms:"Apakah yang dimaksudkan dengan 'tarikh edaran'?",vi:"'Hạn sử dụng để bán' nghĩa là gì?",id:"Apa yang dimaksud dengan 'batas waktu peredaran'?",si:"'බෙදාහැරීමේ කල් ඉකුත්වීමේ දිනය' යනු කුමක්ද?",pt:"O que significa 'prazo de comercialização'?",fr:"Que signifie « date limite de vente » ?",ta:"'விற்பனை காலக்கெடு' என்றால் என்ன?"}],
["판매자가 식품 등의 제품을 소비자에게 팔 수 있는 날짜를 말합니다",{ne:"वितरण म्याद भनेको विक्रेताले खाद्यपदार्थजस्ता उत्पादन उपभोक्तालाई बेच्न सक्ने अन्तिम मिति हो।",bn:"বিক্রয়ের মেয়াদ বলতে বিক্রেতা যে তারিখ পর্যন্ত খাদ্যপণ্যসহ পণ্য ক্রেতার কাছে বিক্রি করতে পারেন সেই তারিখকে বোঝায়।",ru:"Срок реализации — это дата, до которой продавец может продавать потребителю такие товары, как продукты питания.",he:"תאריך אחרון למכירה הוא התאריך שעד אליו המוכר רשאי למכור לצרכן מוצרים כגון מזון.",ms:"Tarikh edaran ialah tarikh sehingga penjual boleh menjual produk seperti makanan kepada pengguna.",vi:"Hạn sử dụng để bán là ngày mà người bán có thể bán các sản phẩm như thực phẩm cho người tiêu dùng.",id:"Batas waktu peredaran adalah tanggal sampai kapan penjual dapat menjual produk seperti makanan kepada konsumen.",si:"බෙදාහැරීමේ කල් ඉකුත්වීමේ දිනය යනු විකුණුම්කරුට ආහාර වැනි නිෂ්පාදන පාරිභෝගිකයාට විකිණිය හැකි දිනයයි.",pt:"O prazo de comercialização é a data até a qual o vendedor pode vender ao consumidor produtos como alimentos.",fr:"La date limite de vente est la date jusqu'à laquelle le vendeur peut vendre au consommateur des produits comme des aliments.",ta:"விற்பனை காலக்கெடு என்பது விற்பனையாளர் உணவு போன்ற பொருட்களை நுகர்வோருக்கு விற்கக்கூடிய கடைசி தேதியைக் குறிக்கிறது."}],
["식품 보관 방법을 잘 지켜야 하는 이유는 무엇입니까?",{ne:"खाद्यपदार्थ भण्डारण गर्ने तरिका राम्ररी पालना गर्नुपर्ने कारण के हो?",bn:"খাদ্য সংরক্ষণের পদ্ধতি ঠিকভাবে মেনে চলতে হবে কেন?",ru:"Почему нужно тщательно соблюдать способы хранения продуктов?",he:"מדוע חשוב להקפיד על שיטות אחסון המזון?",ms:"Mengapakah kaedah penyimpanan makanan perlu dipatuhi dengan baik?",vi:"Vì sao phải tuân thủ tốt cách bảo quản thực phẩm?",id:"Mengapa cara penyimpanan makanan harus dipatuhi dengan baik?",si:"ආහාර ගබඩා කිරීමේ ක්‍රමය හොඳින් පිළිපැදිය යුත්තේ ඇයි?",pt:"Por que é preciso seguir bem os métodos de armazenamento de alimentos?",fr:"Pourquoi faut-il bien respecter les méthodes de conservation des aliments ?",ta:"உணவைச் சேமிக்கும் முறையை நன்றாகப் பின்பற்ற வேண்டியதன் காரணம் என்ன?"}],
["여러분 고향에서는 식품의 유통 기한이 어떻게 표시됩니까?",{ne:"तपाईंको देशमा खाद्यपदार्थको वितरण म्याद कसरी उल्लेख गरिन्छ?",bn:"আপনার দেশে খাদ্যপণ্যের বিক্রয়ের মেয়াদ কীভাবে উল্লেখ করা হয়?",ru:"Как в вашей стране указывается срок реализации продуктов?",he:"כיצד מצוין תאריך המכירה של מזון בארץ מולדתכם?",ms:"Bagaimanakah tarikh edaran makanan ditunjukkan di kampung halaman anda?",vi:"Ở quê hương các bạn, hạn sử dụng của thực phẩm được ghi như thế nào?",id:"Di kampung halaman Anda, bagaimana batas waktu peredaran makanan ditampilkan?",si:"ඔබේ රටේ ආහාරවල බෙදාහැරීමේ කල් ඉකුත්වීමේ දිනය දක්වන්නේ කෙසේද?",pt:"Na sua terra natal, como é indicado o prazo de comercialização dos alimentos?",fr:"Dans votre pays d'origine, comment indique-t-on la date limite de vente des aliments ?",ta:"உங்கள் சொந்த நாட்டில் உணவின் விற்பனை காலக்கெடு எப்படிக் குறிக்கப்படுகிறது?"}],
["네팔에서는 유통 기한을 년, 월, 일로 표시합니다",{ne:"नेपालमा वितरण म्याद वर्ष, महिना र दिनमा उल्लेख गरिन्छ।",bn:"নেপালে বিক্রয়ের মেয়াদ বছর, মাস ও দিন হিসেবে উল্লেখ করা হয়।",ru:"В Непале срок реализации указывается в виде года, месяца и дня.",he:"בנפאל מציינים את תאריך המכירה בשנה, חודש ויום.",ms:"Di Nepal, tarikh edaran ditunjukkan dalam tahun, bulan dan hari.",vi:"Ở Nepal, hạn sử dụng để bán được ghi theo năm, tháng, ngày.",id:"Di Nepal, batas waktu peredaran ditampilkan dalam tahun, bulan, dan hari.",si:"නේපාලයේ බෙදාහැරීමේ කල් ඉකුත්වීමේ දිනය වර්ෂය, මාසය සහ දිනය ලෙස දක්වයි.",pt:"No Nepal, o prazo de comercialização é indicado em ano, mês e dia.",fr:"Au Népal, la date limite de vente est indiquée en année, mois et jour.",ta:"நேபாளத்தில் விற்பனை காலக்கெடு ஆண்டு, மாதம், நாள் என்று குறிக்கப்படுகிறது."}],
["소비 기한은 유통 기한이 지나도 음식을 먹을 수 있는 날짜입니다",{ne:"उपभोग म्याद भनेको वितरण म्याद सकिए पनि खाना खान सकिने मिति हो।",bn:"ব্যবহারের মেয়াদ হলো বিক্রয়ের মেয়াদ পার হলেও যে তারিখ পর্যন্ত খাবার খাওয়া যায় সেই তারিখ।",ru:"Срок годности — это дата, до которой пищу можно есть даже после истечения срока реализации.",he:"תאריך אחרון לצריכה הוא התאריך שעד אליו ניתן לאכול את המזון גם לאחר שעבר תאריך המכירה.",ms:"Tarikh penggunaan ialah tarikh sehingga makanan masih boleh dimakan walaupun tarikh edaran telah berlalu.",vi:"Hạn sử dụng là ngày mà thực phẩm vẫn có thể ăn được dù đã qua hạn để bán.",id:"Batas waktu konsumsi adalah tanggal sampai kapan makanan masih bisa dimakan meski batas waktu peredaran telah lewat.",si:"පරිභෝජන කල් ඉකුත්වීමේ දිනය යනු බෙදාහැරීමේ දිනය පසුවුවද ආහාරය අනුභව කළ හැකි දිනයයි.",pt:"O prazo de consumo é a data até a qual o alimento pode ser consumido mesmo após passar o prazo de comercialização.",fr:"La date limite de consommation est la date jusqu'à laquelle l'aliment peut être consommé même après la date limite de vente.",ta:"நுகர்வு காலக்கெடு என்பது விற்பனை காலக்கெடு முடிந்த பிறகும் உணவை உண்ணக்கூடிய கடைசி தேதி."}],
["무슨 문제가 생긴 것 같아요?",{ne:"के समस्या भएको जस्तो लाग्छ?",bn:"মনে হচ্ছে কী সমস্যা হয়েছে?",ru:"Как вы думаете, какая возникла проблема?",he:"איזו בעיה נראה שהתעוררה?",ms:"Apakah masalah yang nampaknya telah berlaku?",vi:"Bạn thấy có vấn đề gì đã xảy ra?",id:"Menurut Anda, masalah apa yang tampaknya terjadi?",si:"මොනවා ප්‍රශ්නයක් ඇති වුණා වගේද?",pt:"Que problema parece ter surgido?",fr:"Quel problème semble être survenu ?",ta:"என்ன பிரச்சினை ஏற்பட்டதாகத் தோன்றுகிறது?"}],
["여러분은 이런 문제가 생기면 어떻게 해요?",{ne:"तपाईंहरू यस्तो समस्या आयो भने के गर्नुहुन्छ?",bn:"আপনারা এমন সমস্যা হলে কী করেন?",ru:"Что вы делаете, когда возникает такая проблема?",he:"מה אתם עושים כשמתעוררת בעיה כזו?",ms:"Apakah yang anda lakukan apabila masalah seperti ini berlaku?",vi:"Khi gặp vấn đề như thế này, các bạn làm gì?",id:"Apa yang Anda lakukan jika terjadi masalah seperti ini?",si:"මෙවැනි ප්‍රශ්නයක් ඇති වුණොත් ඔබ කරන්නේ කුමක්ද?",pt:"O que vocês fazem quando surge um problema desses?",fr:"Que faites-vous lorsqu'un tel problème survient ?",ta:"இப்படி ஒரு பிரச்சினை ஏற்பட்டால் நீங்கள் என்ன செய்வீர்கள்?"}],
["전자 제품이 고장 나면 어떻게 해요?",{ne:"इलेक्ट्रोनिक सामान बिग्रियो भने के गर्नुहुन्छ?",bn:"ইলেকট্রনিক পণ্য নষ্ট হলে কী করেন?",ru:"Что вы делаете, когда ломается электроприбор?",he:"מה עושים כשמכשיר חשמלי מתקלקל?",ms:"Apakah yang anda lakukan apabila produk elektronik rosak?",vi:"Khi đồ điện tử bị hỏng thì bạn làm gì?",id:"Apa yang Anda lakukan jika produk elektronik rusak?",si:"විද්‍යුත් උපකරණයක් කැඩුණොත් ඔබ කරන්නේ කුමක්ද?",pt:"O que você faz quando um produto eletrônico quebra?",fr:"Que faites-vous lorsqu'un appareil électronique tombe en panne ?",ta:"மின்னணு பொருள் பழுதடைந்தால் நீங்கள் என்ன செய்வீர்கள்?"}]
];
function findKey(sub){
  const ex=list.filter(x=>x.ko===sub);
  if(ex.length===1) return ex[0].ko;
  const m=list.filter(x=>x.ko.indexOf(sub)!==-1);
  if(m.length!==1) throw new Error("substr matched "+m.length+": "+sub);
  return m[0].ko;
}
const batch={};
NE.forEach(([sub,ne])=>{ batch[findKey(sub)]={ne}; });
FULL.forEach(([sub,obj])=>{ batch[findKey(sub)]=obj; });
fs.writeFileSync("_batch.json", JSON.stringify(batch,null,1));
console.log("built batch with", Object.keys(batch).length, "keys");
