const fs=require("fs");
const KEYS=fs.readFileSync("_misskeys_json.txt","utf8").split(/\r?\n/).filter(Boolean).map(l=>JSON.parse(l));
const KEYSET=new Set(KEYS);
const items=[
["어디가 고장 났어요?",{ne:"कहाँ बिग्रेको छ?",bn:"কোথায় নষ্ট হয়েছে?",ru:"Что сломалось?",he:"מה התקלקל?",ms:"Apa yang rosak?",vi:"Chỗ nào bị hỏng?",id:"Bagian mana yang rusak?",si:"මොකද්ද කැඩිලා තියෙන්නේ?",pt:"O que está com defeito?",fr:"Qu'est-ce qui est en panne ?",ta:"எது பழுதாகி உள்ளது?"}],
["어떻게 해야 되나요?",{ne:"के गर्नुपर्छ?",bn:"কী করতে হবে?",ru:"Что мне делать?",he:"מה עליי לעשות?",ms:"Apa yang perlu saya lakukan?",vi:"Tôi phải làm thế nào?",id:"Apa yang harus saya lakukan?",si:"මම කුමක් කළ යුතුද?",pt:"O que devo fazer?",fr:"Que dois-je faire ?",ta:"நான் என்ன செய்ய வேண்டும்?"}],
["수리하는 데 얼마나 걸리나요?",{ne:"मर्मत गर्न कति समय लाग्छ?",bn:"মেরামত করতে কতক্ষণ লাগবে?",ru:"Сколько времени займёт ремонт?",he:"כמה זמן ייקח התיקון?",ms:"Berapa lama masa yang diperlukan untuk pembaikan?",vi:"Việc sửa chữa mất bao lâu?",id:"Berapa lama waktu yang dibutuhkan untuk perbaikan?",si:"අලුත්වැඩියාවට කොපමණ කාලයක් ගතවෙනවාද?",pt:"Quanto tempo leva o conserto?",fr:"Combien de temps prend la réparation ?",ta:"பழுது நீக்க எவ்வளவு நேரம் ஆகும்?"}],
["수리 비용이 많이 비싼가요?",{ne:"मर्मत खर्च धेरै महँगो छ?",bn:"মেরামতের খরচ কি অনেক বেশি?",ru:"Ремонт стоит очень дорого?",he:"האם עלות התיקון גבוהה מאוד?",ms:"Adakah kos pembaikan sangat mahal?",vi:"Chi phí sửa chữa có đắt không?",id:"Apakah biaya perbaikannya sangat mahal?",si:"අලුත්වැඩියා ගාස්තුව ගොඩක් මිල අධිකද?",pt:"O custo do conserto é muito caro?",fr:"Le coût de la réparation est-il très élevé ?",ta:"பழுது சரிசெய்யும் கட்டணம் மிகவும் அதிகமா?"}],
["무상 수리를 받을 수 있나요?",{ne:"निःशुल्क मर्मत पाउन सकिन्छ?",bn:"বিনামূল্যে মেরামত করা যাবে কি?",ru:"Можно ли получить бесплатный ремонт?",he:"האם אפשר לקבל תיקון חינם?",ms:"Bolehkah saya mendapat pembaikan percuma?",vi:"Tôi có thể được sửa chữa miễn phí không?",id:"Apakah saya bisa mendapatkan perbaikan gratis?",si:"නොමිලේ අලුත්වැඩියාවක් ලබාගත හැකිද?",pt:"Posso obter um conserto gratuito?",fr:"Puis-je bénéficier d'une réparation gratuite ?",ta:"இலவசமாக பழுது சரிசெய்ய முடியுமா?"}],
["아나이스 씨가 서비스 센터 직원과 이야기합니다.",{ne:"अनाइस जी सेवा केन्द्रका कर्मचारीसँग कुरा गर्नुहुन्छ।",bn:"আনাইস সার্ভিস সেন্টারের কর্মীর সাথে কথা বলছেন।",ru:"Анаис разговаривает с сотрудником сервисного центра.",he:"אנאיס משוחחת עם עובד מרכז השירות.",ms:"Anaïs bercakap dengan pekerja pusat servis.",vi:"Anaïs nói chuyện với nhân viên trung tâm dịch vụ.",id:"Anaïs berbicara dengan petugas pusat layanan.",si:"අනායිස් සේවා මධ්‍යස්ථානයේ සේවකයා සමඟ කතා කරයි.",pt:"Anaïs conversa com um funcionário do centro de atendimento.",fr:"Anaïs parle avec un employé du centre de service.",ta:"அனாயிஸ் சேவை மையத்தின் ஊழியருடன் பேசுகிறார்."}],
["혹시 다른 문제는 없으셨어요?",{ne:"अरू कुनै समस्या त थिएन?",bn:"অন্য কোনো সমস্যা কি ছিল?",ru:"Были ли какие-то другие проблемы?",he:"האם היו בעיות אחרות?",ms:"Adakah terdapat sebarang masalah lain?",vi:"Anh/chị có gặp vấn đề nào khác không?",id:"Apakah ada masalah lain?",si:"වෙන කිසි ප්‍රශ්නයක් තිබුණේ නැද්ද?",pt:"Houve algum outro problema?",fr:"Avez-vous eu d'autres problèmes ?",ta:"வேறு ஏதேனும் பிரச்சினை இருந்ததா?"}],
["며칠 전부터 속도가 좀 느려졌어요.",{ne:"केही दिन अगाडिदेखि गति अलिकति सुस्त भएको छ।",bn:"কয়েক দিন আগে থেকে গতি একটু কমে গেছে।",ru:"Несколько дней назад скорость немного снизилась.",he:"כבר כמה ימים המהירות ירדה קצת.",ms:"Sejak beberapa hari lalu, kelajuannya menjadi agak perlahan.",vi:"Từ mấy hôm trước tốc độ đã chậm đi một chút.",id:"Sejak beberapa hari lalu kecepatannya agak melambat.",si:"දවස් කීපයකට කලින් ඉඳන් වේගය ටිකක් අඩු වෙලා.",pt:"Há alguns dias a velocidade ficou um pouco mais lenta.",fr:"Depuis quelques jours, la vitesse a un peu ralenti.",ta:"சில நாட்களாக வேகம் கொஞ்சம் குறைந்துவிட்டது."}],
["그럼 예약 좀 부탁드려요.",{ne:"त्यसो भए बुकिङ गरिदिनुहोस् है।",bn:"তাহলে একটা অ্যাপয়েন্টমেন্ট করে দিন।",ru:"Тогда, пожалуйста, оформите запись.",he:"אז אבקש לקבוע תור, בבקשה.",ms:"Kalau begitu, tolong buatkan temu janji.",vi:"Vậy thì phiền anh/chị đặt lịch giúp tôi.",id:"Kalau begitu, tolong buatkan reservasi.",si:"එහෙනම් වෙන්කරවා ගැනීමක් කරන්න.",pt:"Então, por favor, faça um agendamento.",fr:"Alors, veuillez prendre un rendez-vous, s'il vous plaît.",ta:"அப்படியானால், தயவுசெய்து முன்பதிவு செய்யுங்கள்."}],
["텔레비전과 냉장고가 고장 났습니다.",{ne:"टेलिभिजन र रेफ्रिजरेटर बिग्रिएको छ।",bn:"টেলিভিশন এবং রেফ্রিজারেটর নষ্ট হয়ে গেছে।",ru:"Телевизор и холодильник сломались.",he:"הטלוויזיה והמקרר התקלקלו.",ms:"Televisyen dan peti sejuk telah rosak.",vi:"Ti vi và tủ lạnh đã bị hỏng.",id:"Televisi dan kulkas rusak.",si:"රූපවාහිනිය සහ ශීතකරණය කැඩිලා තියෙනවා.",pt:"A televisão e a geladeira quebraram.",fr:"La télévision et le réfrigérateur sont en panne.",ta:"தொலைக்காட்சியும் குளிர்சாதனப் பெட்டியும் பழுதாகிவிட்டன."}],
["제가 잠시 점검해 보겠습니다.",{ne:"म एकछिन जाँच गर्छु।",bn:"আমি একটু পরীক্ষা করে দেখছি।",ru:"Я сейчас проверю.",he:"אני אבדוק רגע.",ms:"Saya akan periksa sebentar.",vi:"Tôi sẽ kiểm tra một chút.",id:"Saya akan memeriksanya sebentar.",si:"මම ටිකක් පරීක්ෂා කර බලන්නම්.",pt:"Vou verificar um momento.",fr:"Je vais vérifier un instant.",ta:"நான் சிறிது நேரம் பரிசோதித்துப் பார்க்கிறேன்."}],
["액정만 바꾸면 문제없을 것 같습니다.",{ne:"स्क्रिन मात्र बदल्यो भने समस्या हुँदैन जस्तो लाग्छ।",bn:"শুধু স্ক্রিন বদলালেই কোনো সমস্যা হবে না বলে মনে হয়।",ru:"Думаю, если заменить только экран, проблем не будет.",he:"נראה שאם רק נחליף את המסך, לא תהיה בעיה.",ms:"Nampaknya jika hanya menggantikan skrin, tiada masalah.",vi:"Có vẻ chỉ cần thay màn hình là sẽ ổn.",id:"Sepertinya jika hanya mengganti layar, tidak akan ada masalah.",si:"තිරය විතරක් මාරු කළොත් ප්‍රශ්නයක් නැති වේවි කියල හිතෙනවා.",pt:"Parece que, se trocarmos apenas a tela, não haverá problema.",fr:"Il semble qu'en remplaçant seulement l'écran, il n'y aura pas de problème.",ta:"திரையை மட்டும் மாற்றினால் பிரச்சினை இருக்காது என நினைக்கிறேன்."}],
["자세한 안내는 통신사 고객 센터로 문의해 보십시오.",{ne:"विस्तृत जानकारीका लागि टेलिकम कम्पनीको ग्राहक सेवा केन्द्रमा सोध्नुहोस्।",bn:"বিস্তারিত তথ্যের জন্য টেলিকম কোম্পানির গ্রাহক সেবা কেন্দ্রে যোগাযোগ করুন।",ru:"За подробной информацией обращайтесь в центр обслуживания клиентов оператора связи.",he:"לפרטים נוספים, פנו למרכז שירות הלקוחות של חברת התקשורת.",ms:"Untuk maklumat lanjut, sila hubungi pusat khidmat pelanggan syarikat telekomunikasi.",vi:"Để biết thông tin chi tiết, vui lòng liên hệ trung tâm khách hàng của nhà mạng.",id:"Untuk informasi lebih lanjut, silakan hubungi pusat layanan pelanggan operator telekomunikasi.",si:"විස්තර සඳහා දුරකථන සමාගමේ පාරිභෝගික සේවා මධ්‍යස්ථානයෙන් විමසන්න.",pt:"Para informações detalhadas, consulte a central de atendimento da operadora.",fr:"Pour plus de détails, veuillez vous renseigner auprès du service client de votre opérateur.",ta:"விரிவான தகவலுக்கு, தொலைத்தொடர்பு நிறுவனத்தின் வாடிக்கையாளர் மையத்தை தொடர்பு கொள்ளவும்."}],
["가방 안에 있었는데 가방을 떨어뜨려서 깨졌습니다.",{ne:"झोलाभित्र थियो, झोला खसालेकाले फुटेको हो।",bn:"ব্যাগের ভেতরে ছিল, ব্যাগটা পড়ে যাওয়ায় ভেঙে গেছে।",ru:"Он был в сумке и разбился, потому что я уронил сумку.",he:"זה היה בתיק ונשבר כי הפלתי את התיק.",ms:"Ia berada di dalam beg, dan pecah kerana saya menjatuhkan beg itu.",vi:"Nó ở trong túi, và bị vỡ vì tôi làm rơi túi.",id:"Itu ada di dalam tas, dan pecah karena saya menjatuhkan tasnya.",si:"එය බෑග් එක ඇතුළේ තිබුණා, බෑග් එක වැටිලා කැඩුණා.",pt:"Estava dentro da bolsa e quebrou porque deixei a bolsa cair.",fr:"Il était dans le sac et s'est cassé parce que j'ai fait tomber le sac.",ta:"அது பையில் இருந்தது, பையை கீழே விழவைத்ததால் உடைந்துவிட்டது."}],
["고객의 무리한 요구 때문에 갈등이 자주 생겨요.",{ne:"ग्राहकको अनुचित मागका कारण प्रायः द्वन्द्व हुन्छ।",bn:"গ্রাহকের অযৌক্তিক দাবির কারণে প্রায়ই দ্বন্দ্ব দেখা দেয়।",ru:"Из-за необоснованных требований клиентов часто возникают конфликты.",he:"בגלל דרישות מוגזמות של לקוחות נוצרים לעיתים קרובות עימותים.",ms:"Konflik sering timbul disebabkan tuntutan pelanggan yang keterlaluan.",vi:"Xung đột thường xảy ra do những yêu cầu vô lý của khách hàng.",id:"Konflik sering muncul karena tuntutan pelanggan yang berlebihan.",si:"පාරිභෝගිකයන්ගේ අසාධාරණ ඉල්ලීම් නිසා නිතර ගැටුම් ඇතිවෙනවා.",pt:"Conflitos surgem com frequência por causa das exigências excessivas dos clientes.",fr:"Des conflits surviennent souvent à cause des exigences déraisonnables des clients.",ta:"வாடிக்கையாளர்களின் நியாயமற்ற கோரிக்கைகளால் அடிக்கடி மோதல்கள் ஏற்படுகின்றன."}],
["와이파이가 안 되는 것은 일시적인 문제예요.",{ne:"वाइफाइ नचल्नु अस्थायी समस्या हो।",bn:"ওয়াইফাই কাজ না করা একটি সাময়িক সমস্যা।",ru:"То, что Wi-Fi не работает, — это временная проблема.",he:"העובדה שהוויי-פיי לא עובד היא בעיה זמנית.",ms:"Wi-Fi yang tidak berfungsi ialah masalah sementara.",vi:"Việc Wi-Fi không hoạt động là một vấn đề tạm thời.",id:"Wi-Fi yang tidak berfungsi adalah masalah sementara.",si:"වයිෆයි ක්‍රියා නොකිරීම තාවකාලික ප්‍රශ්නයක්.",pt:"O Wi-Fi não funcionar é um problema temporário.",fr:"Le fait que le Wi-Fi ne fonctionne pas est un problème temporaire.",ta:"வைஃபை வேலை செய்யாதது ஒரு தற்காலிக பிரச்சினை."}],
["냉장고가 고장 나면 출장 서비스를 신청하세요.",{ne:"रेफ्रिजरेटर बिग्रियो भने घरमै आउने सेवा माग्नुहोस्।",bn:"রেফ্রিজারেটর নষ্ট হলে বাড়িতে এসে সার্ভিসের জন্য আবেদন করুন।",ru:"Если холодильник сломается, вызовите мастера на дом.",he:"אם המקרר מתקלקל, הזמינו שירות טכנאי לבית.",ms:"Jika peti sejuk rosak, mohon perkhidmatan lawatan ke rumah.",vi:"Nếu tủ lạnh bị hỏng, hãy đăng ký dịch vụ sửa tại nhà.",id:"Jika kulkas rusak, ajukan layanan kunjungan ke rumah.",si:"ශීතකරණය කැඩුණොත් නිවසට පැමිණෙන සේවාවක් ඉල්ලන්න.",pt:"Se a geladeira quebrar, solicite o serviço de atendimento em domicílio.",fr:"Si le réfrigérateur tombe en panne, demandez un service à domicile.",ta:"குளிர்சாதனப் பெட்டி பழுதானால், வீட்டிற்கு வரும் சேவையைக் கோருங்கள்."}],
["제품이 고장 났을 때 여러분은 먼저 무엇을 합니까?",{ne:"उत्पादन बिग्रिँदा तपाईं पहिले के गर्नुहुन्छ?",bn:"পণ্য নষ্ট হলে আপনি প্রথমে কী করেন?",ru:"Что вы делаете в первую очередь, когда изделие ломается?",he:"מה אתם עושים קודם כשמוצר מתקלקל?",ms:"Apabila produk rosak, apakah yang anda lakukan dahulu?",vi:"Khi sản phẩm bị hỏng, bạn làm gì đầu tiên?",id:"Ketika produk rusak, apa yang Anda lakukan pertama kali?",si:"නිෂ්පාදනයක් කැඩුණු විට ඔබ මුලින්ම කරන්නේ කුමක්ද?",pt:"Quando um produto quebra, o que você faz primeiro?",fr:"Quand un produit tombe en panne, que faites-vous d'abord ?",ta:"ஒரு பொருள் பழுதானால், நீங்கள் முதலில் என்ன செய்வீர்கள்?"}],
["온도가 높지 않은가요?",{ne:"तापक्रम उच्च छैन र?",bn:"তাপমাত্রা কি বেশি নয়?",ru:"Не слишком ли высокая температура?",he:"האם הטמפרטורה לא גבוהה?",ms:"Bukankah suhunya tinggi?",vi:"Nhiệt độ có cao không?",id:"Bukankah suhunya tinggi?",si:"උෂ්ණත්වය වැඩි නැද්ද?",pt:"A temperatura não está alta?",fr:"La température n'est-elle pas trop élevée ?",ta:"வெப்பநிலை அதிகமாக இல்லையா?"}],
["냉동이 잘 안 돼요.",{ne:"फ्रिजिङ राम्रोसँग हुँदैन।",bn:"ফ্রিজিং ঠিকমতো হচ্ছে না।",ru:"Заморозка плохо работает.",he:"ההקפאה לא עובדת טוב.",ms:"Pembekuan tidak berfungsi dengan baik.",vi:"Ngăn đông không hoạt động tốt.",id:"Pembekuan tidak berfungsi dengan baik.",si:"ශීත කිරීම හරියට වෙන්නේ නැහැ.",pt:"O congelamento não está funcionando bem.",fr:"La congélation ne fonctionne pas bien.",ta:"உறைபனி சரியாக வேலை செய்யவில்லை."}],
["음식물이 자꾸 녹아요.",{ne:"खानेकुरा बारम्बार पग्लन्छ।",bn:"খাবার বারবার গলে যাচ্ছে।",ru:"Продукты постоянно размораживаются.",he:"האוכל כל הזמן נמס.",ms:"Makanan asyik mencair.",vi:"Thức ăn cứ bị rã đông.",id:"Makanannya terus mencair.",si:"කෑම නිතරම දිය වෙනවා.",pt:"Os alimentos ficam descongelando o tempo todo.",fr:"Les aliments décongèlent sans cesse.",ta:"உணவு அடிக்கடி உருகிவிடுகிறது."}],
["노트북 화면이 안 나와요.",{ne:"ल्यापटपको स्क्रिन आउँदैन।",bn:"ল্যাপটপের স্ক্রিন আসছে না।",ru:"Экран ноутбука не включается.",he:"מסך המחשב הנייד לא נדלק.",ms:"Skrin komputer riba tidak berfungsi.",vi:"Màn hình laptop không hiển thị.",id:"Layar laptop tidak menyala.",si:"ලැප්ටොප් තිරය පෙන්නන්නේ නැහැ.",pt:"A tela do notebook não liga.",fr:"L'écran de l'ordinateur portable ne s'affiche pas.",ta:"லேப்டாப் திரை காட்டவில்லை."}],
["전원을 껐다가 켜 보세요.",{ne:"पावर बन्द गरेर फेरि खोल्नुहोस्।",bn:"পাওয়ার বন্ধ করে আবার চালু করে দেখুন।",ru:"Попробуйте выключить и снова включить питание.",he:"נסו לכבות ולהדליק שוב.",ms:"Cuba matikan kuasa dan hidupkan semula.",vi:"Hãy thử tắt nguồn rồi bật lại.",id:"Coba matikan daya lalu nyalakan kembali.",si:"බලය ක්‍රියා විරහිත කර නැවත ක්‍රියාත්මක කර බලන්න.",pt:"Tente desligar e ligar novamente.",fr:"Essayez d'éteindre puis de rallumer.",ta:"மின்சக்தியை அணைத்து மீண்டும் இயக்கிப் பாருங்கள்."}],
["앱을 종료하거나 불필요한 데이터를 삭제해 보세요.",{ne:"एप बन्द गर्नुहोस् वा नचाहिने डाटा मेटाउनुहोस्।",bn:"অ্যাপ বন্ধ করুন বা অপ্রয়োজনীয় ডেটা মুছে দেখুন।",ru:"Попробуйте закрыть приложения или удалить ненужные данные.",he:"נסו לסגור אפליקציות או למחוק נתונים מיותרים.",ms:"Cuba tutup aplikasi atau padam data yang tidak diperlukan.",vi:"Hãy thử đóng ứng dụng hoặc xóa dữ liệu không cần thiết.",id:"Coba tutup aplikasi atau hapus data yang tidak perlu.",si:"යෙදුම් වසා දමන්න හෝ අනවශ්‍ය දත්ත මකා දමා බලන්න.",pt:"Tente fechar os aplicativos ou excluir dados desnecessários.",fr:"Essayez de fermer les applications ou de supprimer les données inutiles.",ta:"செயலிகளை மூடவும் அல்லது தேவையற்ற தரவை நீக்கிப் பாருங்கள்."}],
["플러그를 잘 꽂았는지 확인해 보세요.",{ne:"प्लग राम्रोसँग घुसाइएको छ कि छैन जाँच गर्नुहोस्।",bn:"প্লাগটি ঠিকমতো লাগানো আছে কিনা পরীক্ষা করুন।",ru:"Проверьте, правильно ли вставлена вилка.",he:"בדקו אם התקע מחובר היטב.",ms:"Semak sama ada palam dipasang dengan betul.",vi:"Hãy kiểm tra xem phích cắm đã cắm chặt chưa.",id:"Periksa apakah steker sudah terpasang dengan benar.",si:"ප්ලග් එක හරියට ගසා තිබේද කියා පරීක්ෂා කර බලන්න.",pt:"Verifique se o plugue está bem conectado.",fr:"Vérifiez si la prise est bien branchée.",ta:"பிளக் சரியாக செருகப்பட்டுள்ளதா என்று பரிசோதிக்கவும்."}],
["플러그를 뽑았다 다시 꽂아 보세요.",{ne:"प्लग निकालेर फेरि घुसाउनुहोस्।",bn:"প্লাগটি খুলে আবার লাগিয়ে দেখুন।",ru:"Попробуйте вынуть вилку и снова вставить.",he:"נסו לנתק את התקע ולחבר אותו מחדש.",ms:"Cuba cabut palam dan pasang semula.",vi:"Hãy thử rút phích cắm ra rồi cắm lại.",id:"Coba cabut steker lalu pasang kembali.",si:"ප්ලග් එක ගලවා නැවත ගසා බලන්න.",pt:"Tente desconectar o plugue e conectá-lo novamente.",fr:"Essayez de débrancher la prise puis de la rebrancher.",ta:"பிளக்கை கழற்றி மீண்டும் செருகிப் பாருங்கள்."}],
["펌프질을 하거나 변기 뚫는 세제를 사용해서 뚫어 보세요.",{ne:"पम्प गर्नुहोस् वा ट्वाइलेट खोल्ने डिटर्जेन्ट प्रयोग गरेर खोल्नुहोस्।",bn:"প্লাঞ্জার দিয়ে পাম্প করুন বা টয়লেট পরিষ্কারের ক্লিনার ব্যবহার করে খুলে দেখুন।",ru:"Попробуйте прочистить вантузом или средством для прочистки унитаза.",he:"נסו לפתוח את הסתימה עם פומפה או בחומר לפתיחת סתימות באסלה.",ms:"Cuba buka sumbatan dengan pam atau guna bahan pencuci penyahsumbat tandas.",vi:"Hãy thử thông bằng cách bơm hoặc dùng chất tẩy thông bồn cầu.",id:"Coba buka sumbatan dengan memompa atau menggunakan cairan pembersih penyumbat toilet.",si:"පොම්ප කිරීමෙන් හෝ වැසිකිළිය විවෘත කරන ද්‍රාවකයක් භාවිතයෙන් විවෘත කර බලන්න.",pt:"Tente desentupir usando um desentupidor ou um produto para desentupir vaso sanitário.",fr:"Essayez de déboucher avec une ventouse ou un produit pour déboucher les toilettes.",ta:"பம்ப் செய்து அல்லது கழிப்பறை அடைப்பு நீக்கும் திரவத்தைப் பயன்படுத்தி அடைப்பை நீக்கிப் பாருங்கள்."}],
["밸브를 열었는지 확인해 보세요.",{ne:"भल्भ खोलिएको छ कि छैन जाँच गर्नुहोस्।",bn:"ভালভটি খোলা আছে কিনা পরীক্ষা করুন।",ru:"Проверьте, открыт ли клапан.",he:"בדקו אם השסתום פתוח.",ms:"Semak sama ada injap telah dibuka.",vi:"Hãy kiểm tra xem van đã mở chưa.",id:"Periksa apakah katupnya sudah terbuka.",si:"කපාටය විවෘත කර තිබේද කියා පරීක්ෂා කර බලන්න.",pt:"Verifique se a válvula está aberta.",fr:"Vérifiez si la vanne est ouverte.",ta:"வால்வு திறந்திருக்கிறதா என்று பரிசோதிக்கவும்."}],
["다음은 인터넷 게시판에 올라온 글입니다.",{ne:"तल इन्टरनेट फोरममा राखिएको लेख छ।",bn:"নিচে ইন্টারনেট ফোরামে পোস্ট করা একটি লেখা দেওয়া হলো।",ru:"Ниже приведено сообщение, размещённое на интернет-форуме.",he:"להלן פוסט שפורסם בפורום באינטרנט.",ms:"Berikut ialah catatan yang dimuat naik di papan forum internet.",vi:"Sau đây là bài viết được đăng trên diễn đàn internet.",id:"Berikut adalah tulisan yang diunggah di forum internet.",si:"පහත දැක්වෙන්නේ අන්තර්ජාල සංසදයක පළ කළ ලිපියකි.",pt:"A seguir está uma postagem publicada em um fórum na internet.",fr:"Voici un message publié sur un forum internet.",ta:"கீழே இணையக் கருத்துப் பலகையில் இடப்பட்ட ஒரு பதிவு உள்ளது."}],
["변기가 막히는 이유는 여러 가지가 있습니다.",{ne:"ट्वाइलेट जाम हुनुका धेरै कारण छन्।",bn:"টয়লেট আটকে যাওয়ার নানা কারণ রয়েছে।",ru:"Есть несколько причин, по которым засоряется унитаз.",he:"יש כמה סיבות לכך שאסלה נסתמת.",ms:"Terdapat pelbagai sebab tandas tersumbat.",vi:"Có nhiều lý do khiến bồn cầu bị nghẹt.",id:"Ada berbagai alasan mengapa toilet tersumbat.",si:"වැසිකිළිය අවහිර වීමට හේතු කිහිපයක් තිබේ.",pt:"Há várias razões pelas quais o vaso sanitário entope.",fr:"Il y a plusieurs raisons pour lesquelles les toilettes se bouchent.",ta:"கழிப்பறை அடைப்பதற்குப் பல காரணங்கள் உள்ளன."}],
["전자 제품을 사면 보증서를 받는다.",{ne:"इलेक्ट्रोनिक सामान किन्दा वारेन्टी प्रमाणपत्र पाइन्छ।",bn:"ইলেকট্রনিক পণ্য কিনলে ওয়ারেন্টি কার্ড পাওয়া যায়।",ru:"Покупая электронное изделие, вы получаете гарантийный талон.",he:"כשקונים מוצר חשמלי מקבלים תעודת אחריות.",ms:"Apabila membeli produk elektronik, anda menerima sijil waranti.",vi:"Khi mua sản phẩm điện tử, bạn nhận được phiếu bảo hành.",id:"Saat membeli produk elektronik, Anda menerima kartu garansi.",si:"විද්‍යුත් උපකරණයක් මිලදී ගන්නා විට වගකීම් සහතිකයක් ලැබේ.",pt:"Ao comprar um produto eletrônico, você recebe um termo de garantia.",fr:"Lorsqu'on achète un produit électronique, on reçoit une garantie.",ta:"மின்னணுப் பொருள் வாங்கும்போது உத்தரவாதச் சான்றிதழ் கிடைக்கும்."}],
["저희 집은 변기를 많이 사용하지도 않는데 너무 자주 막힙니다.",{ne:"हाम्रो घरमा ट्वाइलेट धेरै प्रयोग गर्दैनौं तर धेरै पटक जाम हुन्छ।",bn:"আমাদের বাড়িতে টয়লেট বেশি ব্যবহারও করি না, তবু খুব ঘন ঘন আটকে যায়।",ru:"У нас дома туалетом даже не так часто пользуются, но он слишком часто засоряется.",he:"בבית שלנו לא משתמשים הרבה באסלה, אבל היא נסתמת לעיתים קרובות מדי.",ms:"Rumah kami tidak banyak menggunakan tandas, tetapi ia terlalu kerap tersumbat.",vi:"Nhà tôi không dùng bồn cầu nhiều mà nó lại bị nghẹt quá thường xuyên.",id:"Rumah kami tidak banyak memakai toilet, tetapi terlalu sering tersumbat.",si:"අපේ ගෙදර වැසිකිළිය එච්චර පාවිච්චි කරන්නෙත් නැහැ, ඒත් ගොඩක් වෙලාවට අවහිර වෙනවා.",pt:"Nossa casa nem usa muito o vaso sanitário, mas ele entope com muita frequência.",fr:"Chez nous, on n'utilise pourtant pas beaucoup les toilettes, mais elles se bouchent trop souvent.",ta:"எங்கள் வீட்டில் கழிப்பறையை அதிகம் பயன்படுத்துவதே இல்லை, ஆனாலும் அடிக்கடி அடைத்துக்கொள்கிறது."}],
["사용할 때마다 조심하는데 물이 잘 내려가지 않습니다.",{ne:"प्रयोग गर्दा हरेक पटक होसियार हुन्छु तर पानी राम्रोसँग बग्दैन।",bn:"প্রতিবার ব্যবহার করার সময় সাবধান থাকি, তবু পানি ঠিকমতো নামে না।",ru:"Каждый раз при использовании я осторожен, но вода плохо уходит.",he:"אני נזהר בכל פעם שאני משתמש, אבל המים לא יורדים כמו שצריך.",ms:"Setiap kali menggunakannya saya berhati-hati, tetapi airnya tidak turun dengan baik.",vi:"Mỗi lần dùng tôi đều cẩn thận nhưng nước vẫn không thoát tốt.",id:"Setiap kali memakainya saya berhati-hati, tetapi airnya tidak turun dengan lancar.",si:"පාවිච්චි කරන හැම වෙලාවකම පරිස්සම් වෙනවා, ඒත් වතුර හරියට බැහැල යන්නේ නැහැ.",pt:"Tomo cuidado toda vez que uso, mas a água não escoa bem.",fr:"Je fais attention à chaque utilisation, mais l'eau ne s'écoule pas bien.",ta:"பயன்படுத்தும் ஒவ்வொரு முறையும் கவனமாக இருக்கிறேன், ஆனாலும் தண்ணீர் சரியாக இறங்குவதில்லை."}],
["전문가에게 연락하셔서 점검과 도움을 받으시기 바랍니다.",{ne:"विशेषज्ञलाई सम्पर्क गरेर जाँच र सहयोग लिनुहोस्।",bn:"বিশেষজ্ঞের সাথে যোগাযোগ করে পরীক্ষা ও সহায়তা নিন।",ru:"Пожалуйста, свяжитесь со специалистом, чтобы получить осмотр и помощь.",he:"אנא צרו קשר עם מומחה כדי לקבל בדיקה וסיוע.",ms:"Sila hubungi pakar untuk mendapatkan pemeriksaan dan bantuan.",vi:"Vui lòng liên hệ chuyên gia để được kiểm tra và hỗ trợ.",id:"Silakan hubungi ahli untuk mendapatkan pemeriksaan dan bantuan.",si:"පරීක්ෂාවක් සහ උදව්වක් ලබාගැනීමට විශේෂඥයෙකු අමතන්න.",pt:"Por favor, entre em contato com um especialista para obter inspeção e ajuda.",fr:"Veuillez contacter un expert pour obtenir une inspection et de l'aide.",ta:"பரிசோதனை மற்றும் உதவி பெற ஒரு நிபுணரைத் தொடர்பு கொள்ளவும்."}],
["며칠 전부터 화장실 수도꼭지에서 물이 조금씩 새고 있습니다.",{ne:"केही दिन अगाडिदेखि बाथरुमको धाराबाट पानी थोरै-थोरै चुहिरहेको छ।",bn:"কয়েক দিন আগে থেকে বাথরুমের কল থেকে অল্প অল্প করে পানি চুইয়ে পড়ছে।",ru:"Несколько дней из крана в ванной понемногу течёт вода.",he:"כבר כמה ימים דולפים מעט מים מברז האמבטיה.",ms:"Sejak beberapa hari lalu, air sedikit demi sedikit bocor dari paip tandas.",vi:"Từ mấy hôm trước, nước đã rỉ từng chút một từ vòi nước nhà tắm.",id:"Sejak beberapa hari lalu, air sedikit demi sedikit bocor dari keran kamar mandi.",si:"දවස් කීපයකට කලින් ඉඳන් නාන කාමරයේ කරාමයෙන් වතුර ටිකෙන් ටික කාන්දු වෙනවා.",pt:"Há alguns dias, a água está vazando aos poucos da torneira do banheiro.",fr:"Depuis quelques jours, de l'eau fuit peu à peu du robinet de la salle de bain.",ta:"சில நாட்களாக குளியலறை குழாயில் இருந்து கொஞ்சம் கொஞ்சமாக தண்ணீர் கசிந்து கொண்டிருக்கிறது."}],
["처음에는 별로 심하지 않아서 그냥 두었는데 점점 심해지고 있습니다.",{ne:"सुरुमा त्यति गम्भीर नभएकाले छोडेको थिएँ तर बिस्तारै झन् बिग्रँदै गइरहेको छ।",bn:"প্রথমে তেমন গুরুতর ছিল না বলে রেখে দিয়েছিলাম, কিন্তু ধীরে ধীরে খারাপ হচ্ছে।",ru:"Сначала это было не так серьёзно, и я оставил как есть, но постепенно становится хуже.",he:"בהתחלה זה לא היה חמור אז השארתי, אבל זה הולך ומחמיר.",ms:"Pada mulanya tidak begitu teruk jadi saya biarkan sahaja, tetapi ia semakin teruk.",vi:"Lúc đầu không nghiêm trọng nên tôi để mặc, nhưng dần dần ngày càng nặng hơn.",id:"Awalnya tidak terlalu parah jadi saya biarkan, tetapi lama-lama semakin parah.",si:"මුලින් එච්චර දරුණු නොවුණු නිසා අත ඇරලා තිබ්බා, ඒත් ටිකෙන් ටික දරුණු වෙනවා.",pt:"No início não era grave, então deixei assim, mas está piorando aos poucos.",fr:"Au début, ce n'était pas grave, alors je l'ai laissé, mais cela empire peu à peu.",ta:"முதலில் அவ்வளவு மோசமாக இல்லாததால் அப்படியே விட்டேன், ஆனால் படிப்படியாக மோசமாகிக் கொண்டிருக்கிறது."}],
["가능하면 빨리 확인하고 수리해 주시면 감사하겠습니다.",{ne:"सम्भव भए चाँडो जाँच गरी मर्मत गरिदिनुभयो भने आभारी हुनेछु।",bn:"সম্ভব হলে দ্রুত পরীক্ষা করে মেরামত করে দিলে কৃতজ্ঞ থাকব।",ru:"Буду благодарен, если вы как можно скорее проверите и почините это.",he:"אודה לכם אם תוכלו לבדוק ולתקן זאת בהקדם האפשרי.",ms:"Saya amat berterima kasih jika anda dapat memeriksa dan membaikinya secepat mungkin.",vi:"Tôi rất cảm ơn nếu quý vị có thể kiểm tra và sửa chữa sớm nhất có thể.",id:"Saya akan sangat berterima kasih jika Anda dapat memeriksa dan memperbaikinya secepatnya.",si:"හැකි ඉක්මනින් පරීක්ෂා කර අලුත්වැඩියා කර දුන්නොත් ස්තූතිවන්ත වෙනවා.",pt:"Ficaria grato se pudesse verificar e consertar o mais rápido possível.",fr:"Je vous serais reconnaissant de bien vouloir vérifier et réparer cela au plus vite.",ta:"முடிந்தால் விரைவில் பரிசோதித்து சரிசெய்து தந்தால் நன்றியுடையவனாக இருப்பேன்."}],
["언제든지 연락 주시면 집에서 기다리겠습니다.",{ne:"जुनसुकै बेला सम्पर्क गर्नुभयो भने म घरमै पर्खिनेछु।",bn:"যেকোনো সময় যোগাযোগ করলে আমি বাড়িতে অপেক্ষা করব।",ru:"Если свяжетесь со мной в любое время, я буду ждать дома.",he:"אם תיצרו קשר בכל עת, אחכה בבית.",ms:"Jika anda menghubungi bila-bila masa, saya akan menunggu di rumah.",vi:"Nếu quý vị liên hệ bất cứ lúc nào, tôi sẽ đợi ở nhà.",id:"Jika Anda menghubungi kapan saja, saya akan menunggu di rumah.",si:"ඕනෑම වෙලාවක අමතන්න, මම ගෙදර ඉඳන් බලාගෙන ඉන්නම්.",pt:"Se entrar em contato a qualquer momento, esperarei em casa.",fr:"Si vous me contactez à tout moment, j'attendrai à la maison.",ta:"எப்போது வேண்டுமானாலும் தொடர்பு கொண்டால், நான் வீட்டில் காத்திருப்பேன்."}],
["저는 305호에 사는 세입자입니다.",{ne:"म ३०५ नम्बर कोठामा बस्ने भाडावाला हुँ।",bn:"আমি ৩০৫ নম্বর ফ্ল্যাটে বসবাসকারী একজন ভাড়াটে।",ru:"Я — арендатор, живущий в квартире 305.",he:"אני דייר שגר בדירה 305.",ms:"Saya penyewa yang tinggal di unit 305.",vi:"Tôi là người thuê nhà sống ở căn hộ số 305.",id:"Saya penyewa yang tinggal di unit 305.",si:"මම 305 නිවසේ පදිංචි කුලීකරුවෙක්.",pt:"Sou um inquilino que mora na unidade 305.",fr:"Je suis un locataire qui habite au logement 305.",ta:"நான் 305ஆம் எண் வீட்டில் வசிக்கும் வாடகைதாரர்."}],
["집이 오래되어서 그런지 벽에서 물이 새요.",{ne:"घर पुरानो भएर होला, भित्ताबाट पानी चुहिन्छ।",bn:"বাড়িটা পুরনো বলেই হয়তো দেয়াল থেকে পানি চুইয়ে পড়ছে।",ru:"Наверное, потому что дом старый, вода протекает из стены.",he:"אולי בגלל שהבית ישן, נוזלים מים מהקיר.",ms:"Mungkin kerana rumah sudah lama, air bocor dari dinding.",vi:"Có lẽ vì nhà cũ nên nước rỉ ra từ tường.",id:"Mungkin karena rumahnya sudah tua, air merembes dari dinding.",si:"ගෙදර පරණ නිසා වෙන්න ඇති, බිත්තියෙන් වතුර කාන්දු වෙනවා.",pt:"Talvez por a casa ser antiga, a água vaza da parede.",fr:"C'est peut-être parce que la maison est vieille, mais l'eau s'infiltre du mur.",ta:"வீடு பழையதாக இருப்பதால் இருக்கலாம், சுவரில் இருந்து தண்ணீர் கசிகிறது."}]
];
const out={}; const problems=[];
items.forEach(([find,t])=>{
  let key=null;
  if(KEYSET.has(find)) key=find;
  else { const c=KEYS.filter(k=>k.indexOf(find)!==-1); if(c.length===1) key=c[0]; }
  if(!key){ problems.push(find); return; }
  out[key]=t;
});
fs.writeFileSync("_batch.json", JSON.stringify(out,null,1));
console.log("built entries:", Object.keys(out).length, "of", items.length);
if(problems.length){ console.log("UNRESOLVED:"); problems.forEach(p=>console.log("  "+p)); }
