const fs=require("fs");
const lines=fs.readFileSync("_all.txt","utf8").split("\n").filter(Boolean);
function clean(k){
  if(/[�]/.test(k)) return false;
  if(/[0-9]/.test(k)) return false;
  if(/[<>\[\]|①②③④⑤∙ㆍ•]/.test(k)) return false;
  if(/->|=>/.test(k)) return false;
  if(k.replace(/[^가-힣]/g,"").length < 6) return false;
  return true;
}
const cleanKeys=[];
for(const l of lines){ const k=l.split(" :: ")[0]; if(clean(k)) cleanKeys.push(k); }

const T={};
T[44]={ne:"이 링: मेरो बच्चाले तरकारी राम्ररी नखाने भएकाले म चिन्तित छु। अजेला: त्यसैले म तरकारीले भुटेको भात बनाएर बच्चालाई खुवाउँछु।",bn:"ই লিং: আমার বাচ্চা ঠিকমতো সবজি খায় না বলে আমি চিন্তিত। আজেলা: তাই আমি সবজি দিয়ে ভাজা ভাত বানিয়ে বাচ্চাকে খাওয়াই।",ru:"И Лин: Мой ребёнок плохо ест овощи, поэтому я переживаю. Азела: Поэтому я готовлю жареный рис с овощами и кормлю им ребёнка.",he:"יי לינג: הילד שלי לא אוכל ירקות טוב, אז אני מודאגת. אזלה: לכן אני מכינה אורז מטוגן עם ירקות ומאכילה בו את הילד.",ms:"Yi Ling: Anak saya tidak makan sayur dengan baik, jadi saya risau. Azela: Sebab itu saya buat nasi goreng dengan sayur dan suapkan kepada anak saya.",vi:"Yi Ling: Con tôi không chịu ăn rau nên tôi lo lắng. Azela: Vì vậy tôi làm cơm chiên với rau rồi cho con ăn.",id:"Yi Ling: Anak saya tidak mau makan sayur, jadi saya khawatir. Azela: Karena itu saya membuat nasi goreng dengan sayur lalu menyuapkannya ke anak saya.",si:"යී ලින්: මගේ දරුවා එළවළු හොඳට කන්නේ නැති නිසා මම කනස්සල්ලෙන් ඉන්නවා. අසේලා: ඒ නිසා මම එළවළු දාලා ෆ්‍රයිඩ් රයිස් හදලා දරුවාට කවනවා.",pt:"Yi Ling: Meu filho não come bem os legumes, por isso fico preocupada. Azela: Por isso eu faço arroz frito com legumes e dou para o meu filho comer.",fr:"Yi Ling : Mon enfant ne mange pas bien les légumes, alors je m'inquiète. Azela : C'est pourquoi je prépare du riz sauté aux légumes et je le donne à manger à mon enfant.",ta:"யி லிங்: என் குழந்தை காய்கறிகளை நன்றாக சாப்பிடுவதில்லை, அதனால் நான் கவலைப்படுகிறேன். அஜெலா: அதனால் நான் காய்கறிகளுடன் வறுத்த சாதம் செய்து குழந்தைக்கு ஊட்டுகிறேன்."};
T[70]={ne:"इलियाङ: ल्यापटप बिग्रेकाले सर्भिस सेन्टर जान लागेको हुँ, आरक्षण गर्नुपर्छ?",bn:"ইলিয়াং: ল্যাপটপ নষ্ট হয়ে যাওয়ায় সার্ভিস সেন্টারে যেতে চাইছি, আমাকে কি অ্যাপয়েন্টমেন্ট নিতে হবে?",ru:"Илян: У меня сломался ноутбук, и я собираюсь в сервисный центр — нужно ли записываться заранее?",he:"איליאנג: המחשב הנייד שלי התקלקל ואני מתכוון ללכת למרכז השירות — האם צריך לקבוע תור?",ms:"Yiliang: Komputer riba saya rosak jadi saya nak ke pusat servis, perlukah saya buat temu janji?",vi:"Yiliang: Máy tính xách tay của tôi bị hỏng nên tôi định đến trung tâm bảo hành, tôi có cần đặt lịch hẹn không?",id:"Yiliang: Laptop saya rusak jadi saya mau ke pusat servis, apakah saya perlu membuat janji?",si:"ඉලියෑං: මගේ ලැප්ටොප් එක කැඩිලා තියෙන නිසා සර්විස් සෙන්ටර් එකට යන්න හදනවා, මට වෙලාවක් වෙන්කරගන්න ඕනද?",pt:"Yiliang: Meu notebook quebrou, então vou ao centro de assistência — preciso agendar horário?",fr:"Yiliang : Mon ordinateur portable est en panne, je compte aller au centre de service — dois-je prendre rendez-vous ?",ta:"இலியாங்: என் மடிக்கணினி பழுதடைந்ததால் சேவை மையத்திற்குச் செல்ல நினைக்கிறேன், நான் முன்பதிவு செய்ய வேண்டுமா?"};
T[71]={ne:"तलको अवस्थामा थाहा पाउन चाहेको कुरा उदाहरणमा जस्तै मर्मत गर्ने प्राविधिकलाई सोध्नुहोस्।",bn:"নিচের পরিস্থিতিতে আপনি যা জানতে চান তা উদাহরণের মতো করে মেরামতকারীকে জিজ্ঞাসা করুন।",ru:"В следующей ситуации спросите мастера по ремонту о том, что хотите узнать, как в примере.",he:"במצב הבא, שאל את טכנאי התיקונים על מה שאתה רוצה לדעת, כמו בדוגמה.",ms:"Dalam situasi berikut, tanyakan kepada juruteknik pembaikan tentang apa yang anda ingin tahu, seperti dalam contoh.",vi:"Trong tình huống sau, hãy hỏi thợ sửa chữa về điều bạn muốn biết, giống như trong ví dụ.",id:"Dalam situasi berikut, tanyakan kepada teknisi perbaikan tentang hal yang ingin Anda ketahui, seperti pada contoh.",si:"පහත තත්ත්වයේදී ඔබ දැනගන්න කැමති දේ උදාහරණයේ ආකාරයට අළුත්වැඩියා කරන කාර්මිකයාගෙන් අහන්න.",pt:"Na situação a seguir, pergunte ao técnico de reparos o que você quer saber, como no exemplo.",fr:"Dans la situation suivante, posez au technicien de réparation la question sur ce que vous voulez savoir, comme dans l'exemple.",ta:"பின்வரும் சூழ்நிலையில், நீங்கள் அறிய விரும்புவதை எடுத்துக்காட்டில் உள்ளதுபோல் பழுதுபார்க்கும் தொழில்நுட்பரிடம் கேளுங்கள்."};
T[73]={ne:"मर्मत गर्न कति समय लाग्छ?",bn:"মেরামত করতে কতক্ষণ লাগে?",ru:"Сколько времени занимает ремонт?",he:"כמה זמן לוקח התיקון?",ms:"Berapa lama masa yang diambil untuk pembaikan?",vi:"Việc sửa chữa mất bao lâu?",id:"Berapa lama waktu yang dibutuhkan untuk perbaikan?",si:"අළුත්වැඩියාවට කොපමණ කාලයක් ගතවෙනවද?",pt:"Quanto tempo leva o conserto?",fr:"Combien de temps prend la réparation ?",ta:"பழுதுபார்க்க எவ்வளவு நேரம் ஆகும்?"};
T[74]={ne:"के म निःशुल्क मर्मत पाउन सक्छु?",bn:"আমি কি বিনামূল্যে মেরামত পেতে পারি?",ru:"Могу ли я получить бесплатный ремонт?",he:"האם אני יכול לקבל תיקון חינם?",ms:"Bolehkah saya mendapatkan pembaikan percuma?",vi:"Tôi có được sửa chữa miễn phí không?",id:"Apakah saya bisa mendapatkan perbaikan gratis?",si:"මට නොමිලේ අළුත්වැඩියාව ලබාගන්න පුළුවන්ද?",pt:"Posso ter o conserto gratuito?",fr:"Puis-je bénéficier d'une réparation gratuite ?",ta:"எனக்கு இலவச பழுதுபார்ப்பு கிடைக்குமா?"};
T[75]={ne:"चिसो हावा कमजोर छ।",bn:"ঠান্ডা হাওয়া দুর্বল।",ru:"Охлаждение слабое.",he:"הקירור חלש.",ms:"Penyejukan lemah.",vi:"Hơi lạnh yếu.",id:"Hawa dinginnya lemah.",si:"සිසිල්කම දුර්වලයි.",pt:"A refrigeração está fraca.",fr:"Le refroidissement est faible.",ta:"குளிர்ச்சி பலவீனமாக உள்ளது."};
T[76]={ne:"अर्को व्यक्तिलाई प्रश्न सोध्दा प्रयोग गरिने अभिव्यक्ति, नरम र आत्मीय अनुभूति दिन्छ।",bn:"অন্যকে প্রশ্ন করার সময় ব্যবহৃত অভিব্যক্তি, যা নরম ও আন্তরিক অনুভূতি দেয়।",ru:"Выражение, используемое, когда задаёшь собеседнику вопрос; звучит мягко и дружелюбно.",he:"ביטוי המשמש כאשר שואלים את האדם השני שאלה; יש לו תחושה רכה וידידותית.",ms:"Ungkapan yang digunakan semasa bertanya kepada orang lain, memberi perasaan lembut dan mesra.",vi:"Cách nói dùng khi hỏi người khác một câu hỏi, mang cảm giác nhẹ nhàng và thân thiện.",id:"Ungkapan yang digunakan saat bertanya kepada orang lain, memberikan kesan lembut dan akrab.",si:"අනිත් තැනැත්තාගෙන් ප්‍රශ්නයක් අහද්දී භාවිත කරන කියමනක්, මෘදු හා මිත්‍රශීලී හැඟීමක් ලබාදෙයි.",pt:"Uma expressão usada ao fazer uma pergunta à outra pessoa; transmite uma sensação suave e amigável.",fr:"Une expression utilisée pour poser une question à l'autre personne ; elle donne une impression douce et amicale.",ta:"மற்றவரிடம் கேள்வி கேட்கும்போது பயன்படுத்தப்படும் சொற்றொடர்; இது மென்மையான, நட்பான உணர்வைத் தரும்."};
T[77]={ne:"A: यो सप्ताहन्त प्रयोग गर्नुपर्ने छ, मर्मत गर्न कति समय लाग्छ?",bn:"A: এই সপ্তাহান্তে আমার এটা ব্যবহার করতে হবে, ঠিক করতে কতক্ষণ লাগবে?",ru:"A: Мне нужно им пользоваться в эти выходные — сколько времени займёт ремонт?",he:"A: אני צריך להשתמש בזה בסוף השבוע — כמה זמן לוקח לתקן?",ms:"A: Saya perlu menggunakannya hujung minggu ini, berapa lama masa untuk membaikinya?",vi:"A: Cuối tuần này tôi cần dùng nó, sửa mất bao lâu vậy?",id:"A: Saya harus memakainya akhir pekan ini, berapa lama waktu untuk memperbaikinya?",si:"A: මට මේ සති අන්තයේ මේක පාවිච්චි කරන්න ඕන, හදන්න කොපමණ කාලයක් යනවද?",pt:"A: Preciso usá-lo neste fim de semana — quanto tempo leva para consertar?",fr:"A : J'en ai besoin ce week-end — combien de temps faut-il pour le réparer ?",ta:"A: இந்த வார இறுதியில் நான் இதைப் பயன்படுத்த வேண்டும், சரிசெய்ய எவ்வளவு நேரம் ஆகும்?"};
T[78]={ne:"B: करिब दुई दिन लाग्छ।",bn:"B: প্রায় দুই দিন লাগে।",ru:"B: Занимает около двух дней.",he:"B: זה לוקח בערך יומיים.",ms:"B: Ia mengambil masa kira-kira dua hari.",vi:"B: Mất khoảng hai ngày.",id:"B: Membutuhkan waktu sekitar dua hari.",si:"B: දවස් දෙකක් විතර යනවා.",pt:"B: Leva cerca de dois dias.",fr:"B : Cela prend environ deux jours.",ta:"B: சுமார் இரண்டு நாட்கள் ஆகும்."};
T[79]={ne:"मर्मत गर्ने प्राविधिकलाई सोध्नुहोस्।",bn:"মেরামতকারীকে জিজ্ঞাসা করে দেখুন।",ru:"Попробуйте спросить у мастера по ремонту.",he:"נסה לשאול את טכנאי התיקונים.",ms:"Cuba tanya juruteknik pembaikan.",vi:"Hãy thử hỏi thợ sửa chữa.",id:"Coba tanyakan kepada teknisi perbaikan.",si:"අළුත්වැඩියා කරන කාර්මිකයාගෙන් අහලා බලන්න.",pt:"Experimente perguntar ao técnico de reparos.",fr:"Essayez de demander au technicien de réparation.",ta:"பழுதுபார்க்கும் தொழில்நுட்பரிடம் கேட்டுப் பாருங்கள்."};
T[80]={ne:"साथीहरूलाई जिज्ञासा लागेका कुरा सोधेर कुराकानी गर्नुहोस्।",bn:"বন্ধুদের কাছে যা জানতে কৌতূহলী তা জিজ্ঞাসা করে আলোচনা করুন।",ru:"Спросите у друзей о том, что вам интересно, и обсудите это.",he:"שאל את החברים שלך על מה שמסקרן אותך ושוחח על כך.",ms:"Tanyakan kepada rakan-rakan tentang perkara yang anda ingin tahu dan berbual mengenainya.",vi:"Hãy hỏi bạn bè về điều bạn thắc mắc và trò chuyện về nó.",id:"Tanyakan kepada teman-teman tentang hal yang ingin Anda ketahui dan bicarakan.",si:"යාළුවන්ගෙන් ඔබ දැනගන්න කැමති දේ අහලා කතා කරන්න.",pt:"Pergunte aos seus amigos sobre o que você tem curiosidade e converse sobre isso.",fr:"Demandez à vos amis ce qui vous intrigue et discutez-en.",ta:"உங்களுக்குத் தெரிந்துகொள்ள விரும்புவதை நண்பர்களிடம் கேட்டு உரையாடுங்கள்."};
T[82]={ne:"अनाइस: ल्यापटपमा समस्या भएकाले सेवाबारे सोध्न चाहन्थेँ।",bn:"আনাইস: আমার ল্যাপটপে সমস্যা আছে, তাই সার্ভিস সম্পর্কে জিজ্ঞাসা করতে চাইছি।",ru:"Анаис: С моим ноутбуком проблема, поэтому я хотела бы обратиться в сервис.",he:"אנאיס: יש בעיה במחשב הנייד שלי, אז אני רוצה לפנות לשירות.",ms:"Anaïs: Ada masalah dengan komputer riba saya, jadi saya ingin membuat pertanyaan servis.",vi:"Anaïs: Máy tính của tôi có vấn đề nên tôi muốn hỏi về dịch vụ.",id:"Anaïs: Ada masalah dengan laptop saya, jadi saya ingin menanyakan tentang layanan.",si:"අනායිස්: මගේ ලැප්ටොප් එකේ ප්‍රශ්නයක් තියෙන නිසා සේවාව ගැන විමසන්න කැමතියි.",pt:"Anaïs: Há um problema com meu notebook, então gostaria de fazer uma consulta de assistência.",fr:"Anaïs : Mon ordinateur portable a un problème, j'aimerais donc faire une demande de service.",ta:"அனாயிஸ்: என் மடிக்கணினியில் சிக்கல் உள்ளது, எனவே சேவை குறித்து விசாரிக்க விரும்புகிறேன்."};
T[83]={ne:"कर्मचारी: हुन्छ, ग्राहकज्यू, के समस्या छ भन्नुहुन्छ?",bn:"কর্মী: হ্যাঁ, গ্রাহক মহোদয়, কী সমস্যা হয়েছে বলবেন কি?",ru:"Сотрудник: Да, не могли бы вы рассказать, в чём проблема?",he:"נציג: כן, האם תוכל לספר לי מה הבעיה?",ms:"Kakitangan: Ya, boleh encik/puan beritahu apa masalahnya?",vi:"Nhân viên: Vâng, quý khách có thể cho biết vấn đề là gì không ạ?",id:"Petugas: Ya, bisakah Anda memberitahu apa masalahnya?",si:"සේවකයා: ඔව්, පාරිභෝගිකයාණෙනි, මොකක්ද ප්‍රශ්නය කියන්න පුළුවන්ද?",pt:"Atendente: Sim, poderia me dizer qual é o problema?",fr:"Employé : Oui, pourriez-vous me dire quel est le problème ?",ta:"ஊழியர்: ஆம், என்ன பிரச்சனை என்று சொல்ல முடியுமா?"};
T[84]={ne:"अनाइस: हिजोदेखि पावर अन हुँदैन, के गर्नुपर्छ?",bn:"আনাইস: গতকাল থেকে চালু হচ্ছে না, আমি কী করব?",ru:"Анаис: Со вчерашнего дня не включается — что мне делать?",he:"אנאיס: מאתמול זה לא נדלק — מה עליי לעשות?",ms:"Anaïs: Sejak semalam ia tidak boleh dihidupkan, apa yang patut saya buat?",vi:"Anaïs: Từ hôm qua nó không bật lên được, tôi nên làm gì?",id:"Anaïs: Sejak kemarin tidak bisa menyala, apa yang harus saya lakukan?",si:"අනායිස්: ඊයේ ඉඳන් පවර් වෙන්නේ නෑ, මම මොනවද කරන්න ඕන?",pt:"Anaïs: Não liga desde ontem — o que devo fazer?",fr:"Anaïs : Il ne s'allume plus depuis hier — que dois-je faire ?",ta:"அனாயிஸ்: நேற்றிலிருந்து இது இயங்கவில்லை, நான் என்ன செய்ய வேண்டும்?"};
T[85]={ne:"कर्मचारी: समस्या अचानक देखा पर्‍यो?",bn:"কর্মী: সমস্যাটি কি হঠাৎ দেখা দিয়েছে?",ru:"Сотрудник: Проблема возникла внезапно?",he:"נציג: האם הבעיה הופיעה פתאום?",ms:"Kakitangan: Adakah masalah itu berlaku secara tiba-tiba?",vi:"Nhân viên: Vấn đề xảy ra đột ngột phải không ạ?",id:"Petugas: Apakah masalahnya terjadi tiba-tiba?",si:"සේවකයා: ප්‍රශ්නය හදිසියේ ඇතිවුණාද?",pt:"Atendente: O problema surgiu de repente?",fr:"Employé : Le problème est-il apparu soudainement ?",ta:"ஊழியர்: பிரச்சனை திடீரென ஏற்பட்டதா?"};
T[86]={ne:"अनाइस: केही दिनदेखि गति अलि सुस्त भएको छ।",bn:"আনাইস: কয়েকদিন ধরে একটু ধীর হয়ে গেছে।",ru:"Анаис: Уже несколько дней он немного тормозит.",he:"אנאיס: כבר כמה ימים הוא קצת איטי.",ms:"Anaïs: Sejak beberapa hari ia menjadi agak perlahan.",vi:"Anaïs: Mấy ngày nay nó hơi chậm.",id:"Anaïs: Beberapa hari ini agak lambat.",si:"අනායිස්: දවස් කිහිපයක ඉඳන් ටිකක් හෙමින් වෙලා.",pt:"Anaïs: Faz alguns dias que está um pouco lento.",fr:"Anaïs : Depuis quelques jours, il est un peu lent.",ta:"அனாயிஸ்: சில நாட்களாக இது கொஞ்சம் மெதுவாக இருக்கிறது."};
T[87]={ne:"कर्मचारी: ग्राहकज्यू, नजिकैको सेवा केन्द्रमा गएर जाँच गराउनुपर्ने देखिन्छ।",bn:"কর্মী: গ্রাহক মহোদয়, কাছের সার্ভিস সেন্টারে গিয়ে পরীক্ষা করিয়ে নেওয়া উচিত মনে হচ্ছে।",ru:"Сотрудник: Вам стоит посетить ближайший сервисный центр и проверить его.",he:"נציג: כדאי שתבקר במרכז שירות קרוב ותבצע בדיקה.",ms:"Kakitangan: Encik/puan sepatutnya melawat pusat servis berdekatan untuk pemeriksaan.",vi:"Nhân viên: Quý khách nên đến trung tâm bảo hành gần nhất để kiểm tra ạ.",id:"Petugas: Sebaiknya Anda mengunjungi pusat servis terdekat untuk diperiksa.",si:"සේවකයා: පාරිභෝගිකයාණෙනි, ළඟම ඇති සේවා මධ්‍යස්ථානයට ගිහින් පරීක්ෂා කරගන්න ඕන වගේ.",pt:"Atendente: Você deveria visitar um centro de assistência próximo e mandar verificar.",fr:"Employé : Vous devriez vous rendre dans un centre de service proche pour le faire vérifier.",ta:"ஊழியர்: அருகிலுள்ள சேவை மையத்திற்குச் சென்று இதைப் பரிசோதிக்க வேண்டும்."};
T[88]={ne:"अनाइस: ओहो, त्यसो हो?",bn:"আনাইস: ও, তাই নাকি?",ru:"Анаис: О, вот как?",he:"אנאיס: אה, באמת?",ms:"Anaïs: Oh, begitukah?",vi:"Anaïs: À, vậy sao?",id:"Anaïs: Oh, begitu ya?",si:"අනායිස්: ආ, එහෙමද?",pt:"Anaïs: Ah, é mesmo?",fr:"Anaïs : Ah, vraiment ?",ta:"அனாயிஸ்: ஓ, அப்படியா?"};
T[89]={ne:"ग्राहक र सेवा केन्द्रको परामर्श कर्मचारी बनेर कुराकानी गर्नुहोस्।",bn:"একজন গ্রাহক ও সার্ভিস সেন্টারের পরামর্শদাতা কর্মীর ভূমিকা নিয়ে কথোপকথন করুন।",ru:"Сыграйте роли клиента и консультанта сервисного центра и проведите диалог.",he:"שחקו את התפקידים של לקוח ושל יועץ במרכז שירות ונהלו שיחה.",ms:"Mainkan peranan sebagai pelanggan dan kaunselor pusat servis, kemudian berbual.",vi:"Hãy đóng vai khách hàng và nhân viên tư vấn của trung tâm dịch vụ rồi trò chuyện.",id:"Perankan sebagai pelanggan dan konsultan pusat servis, lalu lakukan percakapan.",si:"පාරිභෝගිකයෙක් සහ සේවා මධ්‍යස්ථානයේ උපදේශකයෙක් වෙලා කතාබහ කරන්න.",pt:"Assuma os papéis de um cliente e de um consultor do centro de assistência e conversem.",fr:"Jouez les rôles d'un client et d'un conseiller du centre de service, puis dialoguez.",ta:"ஒரு வாடிக்கையாளர் மற்றும் சேவை மைய ஆலோசகர் பாத்திரங்களை ஏற்று உரையாடுங்கள்."};
T[90]={ne:"टेलिभिजनको पावर अन हुँदैन।",bn:"টেলিভিশন চালু হচ্ছে না।",ru:"Телевизор не включается.",he:"הטלוויזיה לא נדלקת.",ms:"Televisyen tidak boleh dihidupkan.",vi:"Tivi không bật lên được.",id:"Televisi tidak bisa menyala.",si:"රූපවාහිනිය පවර් වෙන්නේ නෑ.",pt:"A televisão não liga.",fr:"La télévision ne s'allume pas.",ta:"தொலைக்காட்சி இயங்கவில்லை."};
T[91]={ne:"राम्ररी जम्दैन।",bn:"ঠিকমতো জমছে না।",ru:"Плохо замораживает.",he:"זה לא מקפיא כמו שצריך.",ms:"Pembekuannya tidak berfungsi dengan baik.",vi:"Không đông đá tốt.",id:"Pembekuannya tidak berfungsi dengan baik.",si:"හරියට ශීත වෙන්නේ නෑ.",pt:"Não congela bem.",fr:"La congélation ne fonctionne pas bien.",ta:"சரியாக உறையவில்லை."};
T[92]={ne:"पहिले फ्रिजरको तापक्रम जाँच्नुहोस्।",bn:"প্রথমে ফ্রিজারের তাপমাত্রা পরীক্ষা করুন।",ru:"Сначала проверьте температуру морозильной камеры.",he:"בדוק תחילה את טמפרטורת המקפיא.",ms:"Periksa suhu peti sejuk beku terlebih dahulu.",vi:"Trước tiên hãy kiểm tra nhiệt độ ngăn đông.",id:"Periksa dulu suhu freezer.",si:"මුලින්ම ශීතකරණයේ (ෆ්‍රීසර්) උෂ්ණත්වය පරීක්ෂා කරන්න.",pt:"Primeiro verifique a temperatura do congelador.",fr:"Vérifiez d'abord la température du congélateur.",ta:"முதலில் உறைவிப்பான் (ஃப்ரீசர்) வெப்பநிலையைச் சரிபார்க்கவும்."};
T[101]={ne:"ग्राहक: टेलिभिजनको पावर अन हुँदैन, के गर्नुपर्छ?",bn:"গ্রাহক: টেলিভিশন চালু হচ্ছে না, আমি কী করব?",ru:"Клиент: Телевизор не включается — что мне делать?",he:"לקוח: הטלוויזיה לא נדלקת — מה עליי לעשות?",ms:"Pelanggan: Televisyen tidak boleh dihidupkan, apa yang patut saya buat?",vi:"Khách hàng: Tivi không bật lên được, tôi nên làm gì?",id:"Pelanggan: Televisi tidak bisa menyala, apa yang harus saya lakukan?",si:"පාරිභෝගිකයා: රූපවාහිනිය පවර් වෙන්නේ නෑ, මම මොනවද කරන්න ඕන?",pt:"Cliente: A televisão não liga — o que devo fazer?",fr:"Client : La télévision ne s'allume pas — que dois-je faire ?",ta:"வாடிக்கையாளர்: தொலைக்காட்சி இயங்கவில்லை, நான் என்ன செய்ய வேண்டும்?"};
T[117]={ne:"रहमान: मोबाइलको स्क्रिन फुटेको छ।",bn:"রহমান: আমার মোবাইলের স্ক্রিন ভেঙে গেছে।",ru:"Рахман: У меня треснул экран телефона.",he:"רחמן: מסך הטלפון שלי סדוק.",ms:"Rahman: Skrin telefon saya pecah.",vi:"Rahman: Màn hình điện thoại của tôi bị vỡ.",id:"Rahman: Layar ponsel saya pecah.",si:"රහ්මාන්: මගේ දුරකථනයේ තිරය කැඩිලා.",pt:"Rahman: A tela do meu celular está rachada.",fr:"Rahman : L'écran de mon téléphone est fissuré.",ta:"ரஹ்மான்: என் தொலைபேசியின் திரை உடைந்துவிட்டது."};
T[118]={ne:"कहिले, कसरी गर्दा फुटेको हो?",bn:"কখন, কীভাবে করতে গিয়ে ভেঙে গেল?",ru:"Когда и как он треснул?",he:"מתי ואיך זה נסדק?",ms:"Bila dan bagaimana ia pecah?",vi:"Nó bị vỡ khi nào và như thế nào?",id:"Kapan dan bagaimana layarnya pecah?",si:"කවදද, කොහොමද වෙද්දිද කැඩුණේ?",pt:"Quando e como ela rachou?",fr:"Quand et comment s'est-il fissuré ?",ta:"எப்போது, எப்படி அது உடைந்தது?"};
T[119]={ne:"रहमान: झोलामा थियो, झोला खसालेकाले त्यसै भयो।",bn:"রহমান: ব্যাগে ছিল, ব্যাগটা ফেলে দেওয়ায় এমন হয়ে গেছে।",ru:"Рахман: Он был в сумке, я уронил сумку, вот так и получилось.",he:"רחמן: הוא היה בתיק, הפלתי את התיק, וכך זה קרה.",ms:"Rahman: Ia ada dalam beg, saya terjatuhkan beg itu, jadi begitulah terjadinya.",vi:"Rahman: Nó ở trong túi, tôi làm rơi túi nên nó bị như vậy.",id:"Rahman: Ada di dalam tas, saya menjatuhkan tasnya, jadi begitulah kejadiannya.",si:"රහ්මාන්: බෑග් එකේ තිබුණා, බෑග් එක බිම වැටිලා එහෙම වුණා.",pt:"Rahman: Estava na bolsa, deixei a bolsa cair e foi assim que aconteceu.",fr:"Rahman : Il était dans mon sac, j'ai fait tomber le sac, et c'est comme ça que c'est arrivé.",ta:"ரஹ்மான்: அது பையில் இருந்தது, பையை கீழே போட்டதால் அப்படி ஆகிவிட்டது."};
T[120]={ne:"कर्मचारी: बुझेँ।",bn:"কর্মী: বুঝেছি।",ru:"Сотрудник: Понятно.",he:"נציג: הבנתי.",ms:"Kakitangan: Baiklah.",vi:"Nhân viên: Tôi hiểu rồi ạ.",id:"Petugas: Baik, saya mengerti.",si:"සේවකයා: තේරුණා.",pt:"Atendente: Entendido.",fr:"Employé : Je comprends.",ta:"ஊழியர்: புரிந்தது."};
T[121]={ne:"झोलाभित्र भएकाले होला, धेरै फुटेको छैन।",bn:"ব্যাগের ভেতরে ছিল বলেই হয়তো, খুব বেশি ভাঙেনি।",ru:"Наверное, из-за того что он был в сумке, он не сильно треснул.",he:"אולי בגלל שהוא היה בתוך התיק, הוא לא נסדק הרבה.",ms:"Mungkin kerana ia berada di dalam beg, ia tidak pecah teruk.",vi:"Có lẽ vì nó ở trong túi nên không bị vỡ nhiều.",id:"Mungkin karena berada di dalam tas, layarnya tidak terlalu pecah.",si:"බෑග් එක ඇතුළේ තිබුණ නිසා වෙන්න ඇති, ලොකුවට කැඩිලා නෑ.",pt:"Talvez porque estava dentro da bolsa, não rachou muito.",fr:"C'est peut-être parce qu'il était dans le sac qu'il n'est pas très fissuré.",ta:"பையின் உள்ளே இருந்ததால் இருக்கலாம், அதிகம் உடையவில்லை."};
T[122]={ne:"रहमान: किन्दा बीमा गरेको थिएँ, कति खर्च लाग्छ?",bn:"রহমান: কেনার সময় বিমা করিয়েছিলাম, খরচ কত পড়বে?",ru:"Рахман: При покупке я оформил страховку — сколько это будет стоить?",he:"רחמן: עשיתי ביטוח כשקניתי — כמה זה יעלה?",ms:"Rahman: Saya ada mengambil insurans semasa membelinya, berapakah kosnya?",vi:"Rahman: Khi mua tôi có mua bảo hiểm, chi phí là bao nhiêu?",id:"Rahman: Saat membeli saya ikut asuransi, berapa biayanya?",si:"රහ්මාන්: ගන්නකොට රක්ෂණයක් කරගත්තා, වියදම කීයක් වෙනවද?",pt:"Rahman: Fiz um seguro quando comprei — quanto vai custar?",fr:"Rahman : J'ai souscrit une assurance à l'achat — combien cela coûtera-t-il ?",ta:"ரஹ்மான்: வாங்கும்போது காப்பீடு எடுத்தேன், செலவு எவ்வளவு ஆகும்?"};
T[123]={ne:"कर्मचारी: मर्मत सकिएपछि रसिद बीमा कम्पनीमा पठाउनुभयो भने ग्राहक अंशभार बाहेकको रकम फिर्ता पाउन सक्नुहुन्छ।",bn:"কর্মী: মেরামত শেষ হওয়ার পর রসিদ বিমা কোম্পানিতে পাঠালে গ্রাহকের নিজের অংশ বাদে টাকা ফেরত পেতে পারেন।",ru:"Сотрудник: После ремонта, если отправите чек в страховую компанию, вам вернут сумму за вычетом вашей франшизы.",he:"נציג: לאחר סיום התיקון, אם תשלח את הקבלה לחברת הביטוח, תוכל לקבל החזר בניכוי ההשתתפות העצמית.",ms:"Kakitangan: Selepas pembaikan selesai, jika anda menghantar resit kepada syarikat insurans, anda boleh dibayar balik selepas ditolak bahagian tanggungan pelanggan.",vi:"Nhân viên: Sau khi sửa xong, nếu gửi hóa đơn cho công ty bảo hiểm, quý khách sẽ được hoàn tiền sau khi trừ phần khách hàng tự chịu.",id:"Petugas: Setelah perbaikan selesai, jika Anda mengirim struk ke perusahaan asuransi, Anda bisa mendapatkan pengembalian dana dikurangi bagian yang ditanggung pelanggan.",si:"සේවකයා: අළුත්වැඩියාව ඉවර වුණාට පස්සේ රිසිට් එක රක්ෂණ සමාගමට යැව්වොත්, පාරිභෝගික දායකත්වය අඩුකරලා ඉතිරිය ආපසු ලබාගන්න පුළුවන්.",pt:"Atendente: Após o conserto, se você enviar o recibo à seguradora, poderá ser reembolsado, descontada a franquia do cliente.",fr:"Employé : Une fois la réparation terminée, si vous envoyez le reçu à l'assureur, vous pourrez être remboursé, déduction faite de la franchise à votre charge.",ta:"ஊழியர்: பழுதுபார்ப்பு முடிந்த பிறகு, ரசீதை காப்பீட்டு நிறுவனத்திற்கு அனுப்பினால், வாடிக்கையாளர் செலுத்த வேண்டிய பங்கைத் தவிர்த்து மீதி தொகையைத் திரும்பப் பெறலாம்."};
T[124]={ne:"मोबाइलमा कस्तो समस्या हुँदा सेवा केन्द्र जानुहुन्छ?",bn:"মোবাইলে কী ধরনের সমস্যা হলে সার্ভিস সেন্টারে যান?",ru:"При какой проблеме с телефоном вы идёте в сервисный центр?",he:"כשאיזו בעיה מתרחשת בטלפון אתה הולך למרכז השירות?",ms:"Apabila masalah apa berlaku pada telefon, anda pergi ke pusat servis?",vi:"Khi điện thoại gặp vấn đề gì thì bạn đến trung tâm dịch vụ?",id:"Ketika masalah seperti apa terjadi pada ponsel, Anda pergi ke pusat servis?",si:"දුරකථනයේ මොන වගේ ප්‍රශ්නයක් ඇතිවුණාම සේවා මධ්‍යස්ථානයට යනවද?",pt:"Quando que tipo de problema ocorre com o celular você vai ao centro de assistência?",fr:"Face à quel type de problème avec le téléphone allez-vous au centre de service ?",ta:"தொலைபேசியில் எந்த வகையான பிரச்சனை ஏற்பட்டால் சேவை மையத்திற்குச் செல்வீர்கள்?"};
T[125]={ne:"रहमानको मोबाइलको स्क्रिन किन फुट्यो?",bn:"রহমানের মোবাইলের স্ক্রিন কেন ভেঙেছিল?",ru:"Почему у Рахмана треснул экран телефона?",he:"מדוע מסך הטלפון של רחמן נסדק?",ms:"Mengapa skrin telefon Rahman pecah?",vi:"Vì sao màn hình điện thoại của Rahman bị vỡ?",id:"Mengapa layar ponsel Rahman pecah?",si:"රහ්මාන්ගේ දුරකථනයේ තිරය ඇයි කැඩුණේ?",pt:"Por que a tela do celular do Rahman rachou?",fr:"Pourquoi l'écran du téléphone de Rahman s'est-il fissuré ?",ta:"ரஹ்மானின் தொலைபேசி திரை ஏன் உடைந்தது?"};
T[128]={ne:"घरमा समस्या आउँदा वा सामान बिग्रँदा प्रायः सोधिने प्रश्नहरू हुन्।",bn:"বাড়িতে সমস্যা হলে বা পণ্য নষ্ট হলে যেসব প্রশ্ন প্রায়ই করা হয়।",ru:"Это часто задаваемые вопросы, когда дома возникает проблема или ломается товар.",he:"אלה שאלות נפוצות כאשר מתעוררת בעיה בבית או כאשר מוצר מתקלקל.",ms:"Ini soalan yang kerap ditanya apabila timbul masalah di rumah atau produk rosak.",vi:"Đây là những câu hỏi thường gặp khi nhà có sự cố hoặc sản phẩm bị hỏng.",id:"Ini adalah pertanyaan yang sering diajukan saat ada masalah di rumah atau produk rusak.",si:"මේවා ගෙදර ප්‍රශ්නයක් ඇතිවුණාම හෝ භාණ්ඩයක් කැඩුණාම නිතර අහන ප්‍රශ්නයි.",pt:"Estas são perguntas frequentes quando surge um problema em casa ou um produto quebra.",fr:"Ce sont des questions fréquemment posées lorsqu'un problème survient à la maison ou qu'un produit tombe en panne.",ta:"வீட்டில் பிரச்சனை ஏற்படும்போது அல்லது பொருள் பழுதடையும்போது அடிக்கடி கேட்கப்படும் கேள்விகள் இவை."};
T[131]={ne:"तापक्रम घटाएर हेर्नुहोस्।",bn:"তাপমাত্রা কমিয়ে দেখুন।",ru:"Попробуйте понизить температуру.",he:"נסה להוריד את הטמפרטורה.",ms:"Cuba turunkan suhu.",vi:"Hãy thử hạ nhiệt độ xuống.",id:"Coba turunkan suhunya.",si:"උෂ්ණත්වය අඩු කරලා බලන්න.",pt:"Experimente baixar a temperatura.",fr:"Essayez de baisser la température.",ta:"வெப்பநிலையைக் குறைத்துப் பாருங்கள்."};
T[133]={ne:"भल्भ खुलेको छ कि छैन जाँच्नुहोस्।",bn:"ভালভটি খোলা আছে কিনা পরীক্ষা করুন।",ru:"Проверьте, открыт ли клапан.",he:"בדוק אם השסתום פתוח.",ms:"Periksa sama ada injap terbuka.",vi:"Hãy kiểm tra xem van đã mở chưa.",id:"Periksa apakah katupnya terbuka.",si:"වෑල්ව් එක ඇරලද කියලා පරීක්ෂා කරන්න.",pt:"Verifique se a válvula está aberta.",fr:"Vérifiez si la vanne est ouverte.",ta:"வால்வு திறந்திருக்கிறதா என்று சரிபார்க்கவும்."};

const out={};
for(const idx of Object.keys(T)){
  const k=cleanKeys[idx];
  if(!k){ console.error("NO KEY for index",idx); continue; }
  out[k]=T[idx];
}
fs.writeFileSync("_batch.json", JSON.stringify(out,null,2));
console.log("wrote items:", Object.keys(out).length);
